# -*- coding: utf-8 -*-
"""sample script for plotting Genesis output

:copyright: Copyright (c) 2015 RadiaBeam Technologies, LLC.  All Rights Reserved.
:license: Apache, see LICENSE for more details.
"""

import h5py, os
import numpy as np
import matplotlib.pyplot as plt

# read the HDF5 file generated by Genesis3 from the LCLS example input deck
file = "lcls.out.h5"
f=h5py.File(file,"r")
l = list(f['energy'])
print(l[0])
'''
# read the energy and energy spread from the file
energy=f['energy'][:]
energy_spread = f['energyspread'][:]
f.close()

# delete plot, if it already exists
plot_name = 'plot_e_de.png'
if os.path.exists(plot_name):
    os.remove(plot_name)

# plot energy spread as a function of energy
plt.scatter(energy_spread,energy)
plt.title('dE/E(E)')
plt.draw()
plt.savefig(plot_name)
# plt.show()
'''
