@set PYTHONPATH=C:\Users\Win\src\radiasoft\radtrack
python test/bunch/testBeam01.py
python test/bunch/testBeam02.py
python test/bunch/testBeam03.py
python test/fields/testUndulatorFields.py
python test/hermite/testHermite01.py
python test/hermite/testHermite02.py
python test/hermite/testHermite03.py
python test/hermite/testHermite04.py
python test/hermite/testHermite05.py
python test/hermite/testHermite06.py
python test/hermite/testHermite07.py
python test/hermite/testHermite08.py
python test/laserHeater/testBorisVay.py
python test/laserHeater/testConstB.py
python test/laserHeater/testConstE.py
python test/laserHeater/testEXB.py
python test/laserHeater/testOscillatingE.py
python test/math/testComplex01.py
python test/math/testComplex02.py
python test/math/testJacobi01.py
python test/matplotlib/testPlot01.py
python test/matplotlib/testSequence01.py
python test/ode/testDrift01.py
python test/ode/testDrift02.py
python test/selfFields/testWake01.py
python test/statistics/testDist01.py
python test/statistics/testLsq01.py
python test/testRunElegantScript/testFun.py
