@set PYTHONPATH=C:\Users\Win\src\radiasoft\radtrack
python examples/bunch/testBeam01.py
python examples/bunch/testBeam02.py
python examples/bunch/testBeam03.py
python examples/fields/testUndulatorFields.py
python examples/hermite/testHermite01.py
python examples/hermite/testHermite02.py
python examples/hermite/testHermite03.py
python examples/hermite/testHermite04.py
python examples/hermite/testHermite05.py
python examples/hermite/testHermite06.py
python examples/hermite/testHermite07.py
python examples/hermite/testHermite08.py
python examples/laserHeater/testBorisVay.py
python examples/laserHeater/testConstB.py
python examples/laserHeater/testConstE.py
python examples/laserHeater/testEXB.py
python examples/laserHeater/testOscillatingE.py
python examples/math/testComplex01.py
python examples/math/testComplex02.py
python examples/math/testJacobi01.py
python examples/matplotlib/testPlot01.py
python examples/matplotlib/testSequence01.py
python examples/ode/testDrift01.py
python examples/ode/testDrift02.py
python examples/selfFields/testWake01.py
python examples/statistics/testDist01.py
python examples/statistics/testLsq01.py
python examples/testRunElegantScript/testFun.py
