# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'genbeam.ui'
#
# Created: Wed Feb 04 10:55:16 2015
#      by: pyside-uic 0.2.14 running on PySide 1.1.2
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_genbeam(object):
    def setupUi(self, genbeam):
        genbeam.setObjectName("genbeam")
        genbeam.resize(323, 389)
        self.formLayoutWidget = QtGui.QWidget(genbeam)
        self.formLayoutWidget.setGeometry(QtCore.QRect(30, 30, 261, 334))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtGui.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.label = QtGui.QLabel(self.formLayoutWidget)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.label)
        self.gamma0 = QtGui.QLineEdit(self.formLayoutWidget)
        self.gamma0.setObjectName("gamma0")
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.gamma0)
        self.label_2 = QtGui.QLabel(self.formLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_2)
        self.delgam = QtGui.QLineEdit(self.formLayoutWidget)
        self.delgam.setObjectName("delgam")
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.delgam)
        self.label_3 = QtGui.QLabel(self.formLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_3)
        self.label_4 = QtGui.QLabel(self.formLayoutWidget)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(3, QtGui.QFormLayout.LabelRole, self.label_4)
        self.label_5 = QtGui.QLabel(self.formLayoutWidget)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(4, QtGui.QFormLayout.LabelRole, self.label_5)
        self.label_6 = QtGui.QLabel(self.formLayoutWidget)
        self.label_6.setObjectName("label_6")
        self.formLayout.setWidget(5, QtGui.QFormLayout.LabelRole, self.label_6)
        self.label_7 = QtGui.QLabel(self.formLayoutWidget)
        self.label_7.setObjectName("label_7")
        self.formLayout.setWidget(6, QtGui.QFormLayout.LabelRole, self.label_7)
        self.label_8 = QtGui.QLabel(self.formLayoutWidget)
        self.label_8.setObjectName("label_8")
        self.formLayout.setWidget(7, QtGui.QFormLayout.LabelRole, self.label_8)
        self.alphax = QtGui.QLineEdit(self.formLayoutWidget)
        self.alphax.setObjectName("alphax")
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.alphax)
        self.alphay = QtGui.QLineEdit(self.formLayoutWidget)
        self.alphay.setObjectName("alphay")
        self.formLayout.setWidget(3, QtGui.QFormLayout.FieldRole, self.alphay)
        self.emitx = QtGui.QLineEdit(self.formLayoutWidget)
        self.emitx.setObjectName("emitx")
        self.formLayout.setWidget(4, QtGui.QFormLayout.FieldRole, self.emitx)
        self.emity = QtGui.QLineEdit(self.formLayoutWidget)
        self.emity.setObjectName("emity")
        self.formLayout.setWidget(5, QtGui.QFormLayout.FieldRole, self.emity)
        self.xbeam = QtGui.QLineEdit(self.formLayoutWidget)
        self.xbeam.setObjectName("xbeam")
        self.formLayout.setWidget(6, QtGui.QFormLayout.FieldRole, self.xbeam)
        self.ybeam = QtGui.QLineEdit(self.formLayoutWidget)
        self.ybeam.setObjectName("ybeam")
        self.formLayout.setWidget(7, QtGui.QFormLayout.FieldRole, self.ybeam)
        self.label_9 = QtGui.QLabel(self.formLayoutWidget)
        self.label_9.setObjectName("label_9")
        self.formLayout.setWidget(12, QtGui.QFormLayout.LabelRole, self.label_9)
        self.curpeak = QtGui.QLineEdit(self.formLayoutWidget)
        self.curpeak.setObjectName("curpeak")
        self.formLayout.setWidget(12, QtGui.QFormLayout.FieldRole, self.curpeak)
        self.label_10 = QtGui.QLabel(self.formLayoutWidget)
        self.label_10.setObjectName("label_10")
        self.formLayout.setWidget(10, QtGui.QFormLayout.LabelRole, self.label_10)
        self.rxbeam = QtGui.QLineEdit(self.formLayoutWidget)
        self.rxbeam.setObjectName("rxbeam")
        self.formLayout.setWidget(10, QtGui.QFormLayout.FieldRole, self.rxbeam)
        self.label_11 = QtGui.QLabel(self.formLayoutWidget)
        self.label_11.setObjectName("label_11")
        self.formLayout.setWidget(11, QtGui.QFormLayout.LabelRole, self.label_11)
        self.rybeam = QtGui.QLineEdit(self.formLayoutWidget)
        self.rybeam.setObjectName("rybeam")
        self.formLayout.setWidget(11, QtGui.QFormLayout.FieldRole, self.rybeam)
        self.label_12 = QtGui.QLabel(self.formLayoutWidget)
        self.label_12.setObjectName("label_12")
        self.formLayout.setWidget(8, QtGui.QFormLayout.LabelRole, self.label_12)
        self.label_13 = QtGui.QLabel(self.formLayoutWidget)
        self.label_13.setObjectName("label_13")
        self.formLayout.setWidget(9, QtGui.QFormLayout.LabelRole, self.label_13)
        self.pxbeam = QtGui.QLineEdit(self.formLayoutWidget)
        self.pxbeam.setObjectName("pxbeam")
        self.formLayout.setWidget(8, QtGui.QFormLayout.FieldRole, self.pxbeam)
        self.pybeam = QtGui.QLineEdit(self.formLayoutWidget)
        self.pybeam.setObjectName("pybeam")
        self.formLayout.setWidget(9, QtGui.QFormLayout.FieldRole, self.pybeam)

        self.retranslateUi(genbeam)
        QtCore.QMetaObject.connectSlotsByName(genbeam)

    def retranslateUi(self, genbeam):
        genbeam.setWindowTitle(QtGui.QApplication.translate("genbeam", "Form", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("genbeam", "Relativistic Factor (beam energy):", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("genbeam", "Energy spread:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("genbeam", "Alpha - x:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("genbeam", "Alpha - y:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("genbeam", "Emittance - x:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("genbeam", "Emittacne - y:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("genbeam", "x:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("genbeam", "y:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("genbeam", "Peak current:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("genbeam", "x rms spatial distribution:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("genbeam", "y rms spatial distribution:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_12.setText(QtGui.QApplication.translate("genbeam", "x\':", None, QtGui.QApplication.UnicodeUTF8))
        self.label_13.setText(QtGui.QApplication.translate("genbeam", "y\':", None, QtGui.QApplication.UnicodeUTF8))

