# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'genfodo.ui'
#
# Created: Mon Feb 02 17:06:41 2015
#      by: pyside-uic 0.2.14 running on PySide 1.1.2
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_genfodo(object):
    def setupUi(self, genfodo):
        genfodo.setObjectName("genfodo")
        genfodo.resize(289, 409)
        self.formLayoutWidget = QtGui.QWidget(genfodo)
        self.formLayoutWidget.setGeometry(QtCore.QRect(30, 30, 231, 341))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtGui.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.label = QtGui.QLabel(self.formLayoutWidget)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.label)
        self.quadf = QtGui.QLineEdit(self.formLayoutWidget)
        self.quadf.setObjectName("quadf")
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.quadf)
        self.label_2 = QtGui.QLabel(self.formLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_2)
        self.quadd = QtGui.QLineEdit(self.formLayoutWidget)
        self.quadd.setObjectName("quadd")
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.quadd)
        self.label_3 = QtGui.QLabel(self.formLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_3)
        self.fl = QtGui.QLineEdit(self.formLayoutWidget)
        self.fl.setObjectName("fl")
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.fl)
        self.label_4 = QtGui.QLabel(self.formLayoutWidget)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(3, QtGui.QFormLayout.LabelRole, self.label_4)
        self.dl = QtGui.QLineEdit(self.formLayoutWidget)
        self.dl.setObjectName("dl")
        self.formLayout.setWidget(3, QtGui.QFormLayout.FieldRole, self.dl)
        self.label_5 = QtGui.QLabel(self.formLayoutWidget)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(4, QtGui.QFormLayout.LabelRole, self.label_5)
        self.drl = QtGui.QLineEdit(self.formLayoutWidget)
        self.drl.setObjectName("drl")
        self.formLayout.setWidget(4, QtGui.QFormLayout.FieldRole, self.drl)
        self.label_6 = QtGui.QLabel(self.formLayoutWidget)
        self.label_6.setObjectName("label_6")
        self.formLayout.setWidget(5, QtGui.QFormLayout.LabelRole, self.label_6)
        self.f1st = QtGui.QLineEdit(self.formLayoutWidget)
        self.f1st.setObjectName("f1st")
        self.formLayout.setWidget(5, QtGui.QFormLayout.FieldRole, self.f1st)
        self.label_7 = QtGui.QLabel(self.formLayoutWidget)
        self.label_7.setObjectName("label_7")
        self.formLayout.setWidget(6, QtGui.QFormLayout.LabelRole, self.label_7)
        self.label_8 = QtGui.QLabel(self.formLayoutWidget)
        self.label_8.setObjectName("label_8")
        self.formLayout.setWidget(7, QtGui.QFormLayout.LabelRole, self.label_8)
        self.qfdx = QtGui.QLineEdit(self.formLayoutWidget)
        self.qfdx.setObjectName("qfdx")
        self.formLayout.setWidget(6, QtGui.QFormLayout.FieldRole, self.qfdx)
        self.qfdy = QtGui.QLineEdit(self.formLayoutWidget)
        self.qfdy.setObjectName("qfdy")
        self.formLayout.setWidget(7, QtGui.QFormLayout.FieldRole, self.qfdy)
        self.label_9 = QtGui.QLabel(self.formLayoutWidget)
        self.label_9.setObjectName("label_9")
        self.formLayout.setWidget(8, QtGui.QFormLayout.LabelRole, self.label_9)
        self.label_10 = QtGui.QLabel(self.formLayoutWidget)
        self.label_10.setObjectName("label_10")
        self.formLayout.setWidget(9, QtGui.QFormLayout.LabelRole, self.label_10)
        self.solen = QtGui.QLineEdit(self.formLayoutWidget)
        self.solen.setObjectName("solen")
        self.formLayout.setWidget(8, QtGui.QFormLayout.FieldRole, self.solen)
        self.sl = QtGui.QLineEdit(self.formLayoutWidget)
        self.sl.setObjectName("sl")
        self.formLayout.setWidget(9, QtGui.QFormLayout.FieldRole, self.sl)

        self.retranslateUi(genfodo)
        QtCore.QMetaObject.connectSlotsByName(genfodo)

    def retranslateUi(self, genfodo):
        genfodo.setWindowTitle(QtGui.QApplication.translate("genfodo", "Form", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("genfodo", "Focusing Quad strength:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("genfodo", "Defocusing Quad strength:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("genfodo", "Focusing Quad length:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("genfodo", "Defocusing Quad length:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("genfodo", "Drift between Quads:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("genfodo", "Starting point:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("genfodo", "Offset - x:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("genfodo", "Offset - y:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("genfodo", "Solenoid field component:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("genfodo", "Solenoid component length:", None, QtGui.QApplication.UnicodeUTF8))

