import h5py
import math
import numpy as np
import matplotlib.pyplot as plt

# read the HDF5 file generated by Genesis3 from the LCLS example input deck
file = "lcls.out.h5"
f=h5py.File(file,"r")

# read the energy and energy spread from the file
energy=f['energy'][:]
energy_spread = f['energyspread'][:]
f.close()

# plot energy spread as a function of energy
plt.scatter(energy_spread,energy)
plt.title('dE/E(E)')
plt.show()
