
from PyQt4 import QtGui, QtCore

class Ui_genund(object):
    def setupUi(self, genund):
        genund.setObjectName("genund")
        genund.resize(300, 350)
        self.formLayoutWidget = QtGui.QWidget(genund)
        self.formLayoutWidget.setGeometry(QtCore.QRect(30, 30, 241, 271))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtGui.QFormLayout(self.formLayoutWidget)
        self.formLayout.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.label = QtGui.QLabel(self.formLayoutWidget)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.label)
        self.iwityp = QtGui.QPushButton(self.formLayoutWidget)
        self.iwityp.setObjectName("iwityp")
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.iwityp)
        self.label_2 = QtGui.QLabel(self.formLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_2)
        self.aw0 = QtGui.QLineEdit(self.formLayoutWidget)
        self.aw0.setObjectName("aw0")
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.aw0)
        self.label_3 = QtGui.QLabel(self.formLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_3)
        self.xlamd = QtGui.QLineEdit(self.formLayoutWidget)
        self.xlamd.setObjectName("xlamd")
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.xlamd)
        self.label_4 = QtGui.QLabel(self.formLayoutWidget)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(3, QtGui.QFormLayout.LabelRole, self.label_4)
        self.nwig = QtGui.QLineEdit(self.formLayoutWidget)
        self.nwig.setObjectName("nwig")
        self.formLayout.setWidget(3, QtGui.QFormLayout.FieldRole, self.nwig)
        self.label_8 = QtGui.QLabel(self.formLayoutWidget)
        self.label_8.setObjectName("label_8")
        self.formLayout.setWidget(4, QtGui.QFormLayout.LabelRole, self.label_8)
        self.nsec = QtGui.QLineEdit(self.formLayoutWidget)
        self.nsec.setObjectName("nsec")
        self.formLayout.setWidget(4, QtGui.QFormLayout.FieldRole, self.nsec)
        self.label_5 = QtGui.QLabel(self.formLayoutWidget)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(5, QtGui.QFormLayout.LabelRole, self.label_5)
        self.label_6 = QtGui.QLabel(self.formLayoutWidget)
        self.label_6.setObjectName("label_6")
        self.formLayout.setWidget(6, QtGui.QFormLayout.LabelRole, self.label_6)
        self.awx = QtGui.QLineEdit(self.formLayoutWidget)
        self.awx.setObjectName("awx")
        self.formLayout.setWidget(6, QtGui.QFormLayout.FieldRole, self.awx)
        self.label_7 = QtGui.QLabel(self.formLayoutWidget)
        self.label_7.setObjectName("label_7")
        self.formLayout.setWidget(7, QtGui.QFormLayout.LabelRole, self.label_7)
        self.awy = QtGui.QLineEdit(self.formLayoutWidget)
        self.awy.setObjectName("awy")
        self.formLayout.setWidget(7, QtGui.QFormLayout.FieldRole, self.awy)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.delaw = QtGui.QLineEdit(self.formLayoutWidget)
        self.delaw.setObjectName("delaw")
        self.horizontalLayout.addWidget(self.delaw)
        self.iertyp = QtGui.QSpinBox(self.formLayoutWidget)
        self.iertyp.setObjectName("iertyp")
        self.horizontalLayout.addWidget(self.iertyp)
        self.formLayout.setLayout(5, QtGui.QFormLayout.FieldRole, self.horizontalLayout)
        self.seed = QtGui.QLineEdit(self.formLayoutWidget)
        self.seed.setObjectName("seed")
        self.formLayout.setWidget(8, QtGui.QFormLayout.FieldRole, self.seed)
        self.label_9 = QtGui.QLabel(self.formLayoutWidget)
        self.label_9.setObjectName("label_9")
        self.formLayout.setWidget(8, QtGui.QFormLayout.LabelRole, self.label_9)

        self.retranslateUi(genund)
        QtCore.QMetaObject.connectSlotsByName(genund)

    def retranslateUi(self, genund):
        genund.setWindowTitle(QtGui.QApplication.translate("genund", "Form", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("genund", "Undulator Type:", None, QtGui.QApplication.UnicodeUTF8))
        self.iwityp.setText(QtGui.QApplication.translate("genund", "Planar/Helical", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("genund", "Undulator Parameter:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("genund", "Period Length:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("genund", "Number of Periods:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("genund", "Sections:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("genund", "Field Errors:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("genund", "Offset - x:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("genund", "Offset - y:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("genund", "seed:", None, QtGui.QApplication.UnicodeUTF8))



class Ui_genfodo(object):
    def setupUi(self, genfodo):
        genfodo.setObjectName("genfodo")
        genfodo.resize(289, 409)
        self.formLayoutWidget = QtGui.QWidget(genfodo)
        self.formLayoutWidget.setGeometry(QtCore.QRect(30, 30, 231, 341))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtGui.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.label = QtGui.QLabel(self.formLayoutWidget)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.label)
        self.quadf = QtGui.QLineEdit(self.formLayoutWidget)
        self.quadf.setObjectName("quadf")
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.quadf)
        self.label_2 = QtGui.QLabel(self.formLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_2)
        self.quadd = QtGui.QLineEdit(self.formLayoutWidget)
        self.quadd.setObjectName("quadd")
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.quadd)
        self.label_3 = QtGui.QLabel(self.formLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_3)
        self.fl = QtGui.QLineEdit(self.formLayoutWidget)
        self.fl.setObjectName("fl")
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.fl)
        self.label_4 = QtGui.QLabel(self.formLayoutWidget)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(3, QtGui.QFormLayout.LabelRole, self.label_4)
        self.dl = QtGui.QLineEdit(self.formLayoutWidget)
        self.dl.setObjectName("dl")
        self.formLayout.setWidget(3, QtGui.QFormLayout.FieldRole, self.dl)
        self.label_5 = QtGui.QLabel(self.formLayoutWidget)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(4, QtGui.QFormLayout.LabelRole, self.label_5)
        self.drl = QtGui.QLineEdit(self.formLayoutWidget)
        self.drl.setObjectName("drl")
        self.formLayout.setWidget(4, QtGui.QFormLayout.FieldRole, self.drl)
        self.label_6 = QtGui.QLabel(self.formLayoutWidget)
        self.label_6.setObjectName("label_6")
        self.formLayout.setWidget(5, QtGui.QFormLayout.LabelRole, self.label_6)
        self.f1st = QtGui.QLineEdit(self.formLayoutWidget)
        self.f1st.setObjectName("f1st")
        self.formLayout.setWidget(5, QtGui.QFormLayout.FieldRole, self.f1st)
        self.label_7 = QtGui.QLabel(self.formLayoutWidget)
        self.label_7.setObjectName("label_7")
        self.formLayout.setWidget(6, QtGui.QFormLayout.LabelRole, self.label_7)
        self.label_8 = QtGui.QLabel(self.formLayoutWidget)
        self.label_8.setObjectName("label_8")
        self.formLayout.setWidget(7, QtGui.QFormLayout.LabelRole, self.label_8)
        self.qfdx = QtGui.QLineEdit(self.formLayoutWidget)
        self.qfdx.setObjectName("qfdx")
        self.formLayout.setWidget(6, QtGui.QFormLayout.FieldRole, self.qfdx)
        self.qfdy = QtGui.QLineEdit(self.formLayoutWidget)
        self.qfdy.setObjectName("qfdy")
        self.formLayout.setWidget(7, QtGui.QFormLayout.FieldRole, self.qfdy)
        self.label_9 = QtGui.QLabel(self.formLayoutWidget)
        self.label_9.setObjectName("label_9")
        self.formLayout.setWidget(8, QtGui.QFormLayout.LabelRole, self.label_9)
        self.label_10 = QtGui.QLabel(self.formLayoutWidget)
        self.label_10.setObjectName("label_10")
        self.formLayout.setWidget(9, QtGui.QFormLayout.LabelRole, self.label_10)
        self.solen = QtGui.QLineEdit(self.formLayoutWidget)
        self.solen.setObjectName("solen")
        self.formLayout.setWidget(8, QtGui.QFormLayout.FieldRole, self.solen)
        self.sl = QtGui.QLineEdit(self.formLayoutWidget)
        self.sl.setObjectName("sl")
        self.formLayout.setWidget(9, QtGui.QFormLayout.FieldRole, self.sl)

        self.retranslateUi(genfodo)
        QtCore.QMetaObject.connectSlotsByName(genfodo)

    def retranslateUi(self, genfodo):
        genfodo.setWindowTitle(QtGui.QApplication.translate("genfodo", "Form", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("genfodo", "Focusing Quad strength:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("genfodo", "Defocusing Quad strength:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("genfodo", "Focusing Quad length:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("genfodo", "Defocusing Quad length:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("genfodo", "Drift between Quads:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("genfodo", "Starting point:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("genfodo", "Offset - x:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("genfodo", "Offset - y:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("genfodo", "Solenoid field component:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("genfodo", "Solenoid component length:", None, QtGui.QApplication.UnicodeUTF8))




class Ui_genbeam(object):
    def setupUi(self, genbeam):
        genbeam.setObjectName("genbeam")
        genbeam.resize(323, 389)
        self.formLayoutWidget = QtGui.QWidget(genbeam)
        self.formLayoutWidget.setGeometry(QtCore.QRect(30, 30, 261, 334))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtGui.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.label = QtGui.QLabel(self.formLayoutWidget)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.label)
        self.gamma0 = QtGui.QLineEdit(self.formLayoutWidget)
        self.gamma0.setObjectName("gamma0")
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.gamma0)
        self.label_2 = QtGui.QLabel(self.formLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_2)
        self.delgam = QtGui.QLineEdit(self.formLayoutWidget)
        self.delgam.setObjectName("delgam")
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.delgam)
        self.label_3 = QtGui.QLabel(self.formLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_3)
        self.label_4 = QtGui.QLabel(self.formLayoutWidget)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(3, QtGui.QFormLayout.LabelRole, self.label_4)
        self.label_5 = QtGui.QLabel(self.formLayoutWidget)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(4, QtGui.QFormLayout.LabelRole, self.label_5)
        self.label_6 = QtGui.QLabel(self.formLayoutWidget)
        self.label_6.setObjectName("label_6")
        self.formLayout.setWidget(5, QtGui.QFormLayout.LabelRole, self.label_6)
        self.label_7 = QtGui.QLabel(self.formLayoutWidget)
        self.label_7.setObjectName("label_7")
        self.formLayout.setWidget(6, QtGui.QFormLayout.LabelRole, self.label_7)
        self.label_8 = QtGui.QLabel(self.formLayoutWidget)
        self.label_8.setObjectName("label_8")
        self.formLayout.setWidget(7, QtGui.QFormLayout.LabelRole, self.label_8)
        self.alphax = QtGui.QLineEdit(self.formLayoutWidget)
        self.alphax.setObjectName("alphax")
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.alphax)
        self.alphay = QtGui.QLineEdit(self.formLayoutWidget)
        self.alphay.setObjectName("alphay")
        self.formLayout.setWidget(3, QtGui.QFormLayout.FieldRole, self.alphay)
        self.emitx = QtGui.QLineEdit(self.formLayoutWidget)
        self.emitx.setObjectName("emitx")
        self.formLayout.setWidget(4, QtGui.QFormLayout.FieldRole, self.emitx)
        self.emity = QtGui.QLineEdit(self.formLayoutWidget)
        self.emity.setObjectName("emity")
        self.formLayout.setWidget(5, QtGui.QFormLayout.FieldRole, self.emity)
        self.xbeam = QtGui.QLineEdit(self.formLayoutWidget)
        self.xbeam.setObjectName("xbeam")
        self.formLayout.setWidget(6, QtGui.QFormLayout.FieldRole, self.xbeam)
        self.ybeam = QtGui.QLineEdit(self.formLayoutWidget)
        self.ybeam.setObjectName("ybeam")
        self.formLayout.setWidget(7, QtGui.QFormLayout.FieldRole, self.ybeam)
        self.label_9 = QtGui.QLabel(self.formLayoutWidget)
        self.label_9.setObjectName("label_9")
        self.formLayout.setWidget(12, QtGui.QFormLayout.LabelRole, self.label_9)
        self.curpeak = QtGui.QLineEdit(self.formLayoutWidget)
        self.curpeak.setObjectName("curpeak")
        self.formLayout.setWidget(12, QtGui.QFormLayout.FieldRole, self.curpeak)
        self.label_10 = QtGui.QLabel(self.formLayoutWidget)
        self.label_10.setObjectName("label_10")
        self.formLayout.setWidget(10, QtGui.QFormLayout.LabelRole, self.label_10)
        self.rxbeam = QtGui.QLineEdit(self.formLayoutWidget)
        self.rxbeam.setObjectName("rxbeam")
        self.formLayout.setWidget(10, QtGui.QFormLayout.FieldRole, self.rxbeam)
        self.label_11 = QtGui.QLabel(self.formLayoutWidget)
        self.label_11.setObjectName("label_11")
        self.formLayout.setWidget(11, QtGui.QFormLayout.LabelRole, self.label_11)
        self.rybeam = QtGui.QLineEdit(self.formLayoutWidget)
        self.rybeam.setObjectName("rybeam")
        self.formLayout.setWidget(11, QtGui.QFormLayout.FieldRole, self.rybeam)
        self.label_12 = QtGui.QLabel(self.formLayoutWidget)
        self.label_12.setObjectName("label_12")
        self.formLayout.setWidget(8, QtGui.QFormLayout.LabelRole, self.label_12)
        self.label_13 = QtGui.QLabel(self.formLayoutWidget)
        self.label_13.setObjectName("label_13")
        self.formLayout.setWidget(9, QtGui.QFormLayout.LabelRole, self.label_13)
        self.pxbeam = QtGui.QLineEdit(self.formLayoutWidget)
        self.pxbeam.setObjectName("pxbeam")
        self.formLayout.setWidget(8, QtGui.QFormLayout.FieldRole, self.pxbeam)
        self.pybeam = QtGui.QLineEdit(self.formLayoutWidget)
        self.pybeam.setObjectName("pybeam")
        self.formLayout.setWidget(9, QtGui.QFormLayout.FieldRole, self.pybeam)

        self.retranslateUi(genbeam)
        QtCore.QMetaObject.connectSlotsByName(genbeam)

    def retranslateUi(self, genbeam):
        genbeam.setWindowTitle(QtGui.QApplication.translate("genbeam", "Form", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("genbeam", "Relativistic Factor (beam energy):", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("genbeam", "Energy spread:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("genbeam", "Alpha - x:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("genbeam", "Alpha - y:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("genbeam", "Emittance - x:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("genbeam", "Emittacne - y:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("genbeam", "x:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("genbeam", "y:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("genbeam", "Peak current:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("genbeam", "x rms spatial distribution:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("genbeam", "y rms spatial distribution:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_12.setText(QtGui.QApplication.translate("genbeam", "x\':", None, QtGui.QApplication.UnicodeUTF8))
        self.label_13.setText(QtGui.QApplication.translate("genbeam", "y\':", None, QtGui.QApplication.UnicodeUTF8))





class Ui_radiation(object):
    def setupUi(self, radiation):
        radiation.setObjectName("radiation")
        radiation.resize(371, 281)
        self.formLayoutWidget = QtGui.QWidget(radiation)
        self.formLayoutWidget.setGeometry(QtCore.QRect(30, 30, 311, 221))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtGui.QFormLayout(self.formLayoutWidget)
        self.formLayout.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.label = QtGui.QLabel(self.formLayoutWidget)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.label)
        self.xlamds = QtGui.QLineEdit(self.formLayoutWidget)
        self.xlamds.setObjectName("xlamds")
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.xlamds)
        self.label_2 = QtGui.QLabel(self.formLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_2)
        self.prad0 = QtGui.QLineEdit(self.formLayoutWidget)
        self.prad0.setObjectName("prad0")
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.prad0)
        self.label_3 = QtGui.QLabel(self.formLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_3)
        self.zrayl = QtGui.QLineEdit(self.formLayoutWidget)
        self.zrayl.setObjectName("zrayl")
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.zrayl)
        self.label_4 = QtGui.QLabel(self.formLayoutWidget)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(3, QtGui.QFormLayout.LabelRole, self.label_4)
        self.zwaist = QtGui.QLineEdit(self.formLayoutWidget)
        self.zwaist.setObjectName("zwaist")
        self.formLayout.setWidget(3, QtGui.QFormLayout.FieldRole, self.zwaist)
        self.label_5 = QtGui.QLabel(self.formLayoutWidget)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(4, QtGui.QFormLayout.LabelRole, self.label_5)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.iallharm = QtGui.QPushButton(self.formLayoutWidget)
        self.iallharm.setObjectName("iallharm")
        self.horizontalLayout_2.addWidget(self.iallharm)
        self.nharm = QtGui.QLineEdit(self.formLayoutWidget)
        self.nharm.setObjectName("nharm")
        self.horizontalLayout_2.addWidget(self.nharm)
        self.formLayout.setLayout(4, QtGui.QFormLayout.FieldRole, self.horizontalLayout_2)
        self.label_6 = QtGui.QLabel(self.formLayoutWidget)
        self.label_6.setObjectName("label_6")
        self.formLayout.setWidget(5, QtGui.QFormLayout.LabelRole, self.label_6)
        self.iharmsc = QtGui.QPushButton(self.formLayoutWidget)
        self.iharmsc.setObjectName("iharmsc")
        self.formLayout.setWidget(5, QtGui.QFormLayout.FieldRole, self.iharmsc)
        self.label_7 = QtGui.QLabel(self.formLayoutWidget)
        self.label_7.setObjectName("label_7")
        self.formLayout.setWidget(6, QtGui.QFormLayout.LabelRole, self.label_7)
        self.pradh0 = QtGui.QLineEdit(self.formLayoutWidget)
        self.pradh0.setObjectName("pradh0")
        self.formLayout.setWidget(6, QtGui.QFormLayout.FieldRole, self.pradh0)

        self.retranslateUi(radiation)
        QtCore.QMetaObject.connectSlotsByName(radiation)

    def retranslateUi(self, radiation):
        radiation.setWindowTitle(QtGui.QApplication.translate("radiation", "Form", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("radiation", "Resonant Radiation Wavelength:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("radiation", "Input Radiation Power:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("radiation", "Rayleigh length:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("radiation", "Position of Input Radiation Waist:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("radiation", "Harmonics:", None, QtGui.QApplication.UnicodeUTF8))
        self.iallharm.setText(QtGui.QApplication.translate("radiation", "All Harmonics", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("radiation", "Include Feedback on beam:", None, QtGui.QApplication.UnicodeUTF8))
        self.iallharm.setText(QtGui.QApplication.translate("radiation", "Yes/No", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("radiation", "Harmonic Radiation Power:", None, QtGui.QApplication.UnicodeUTF8))



class Ui_ploading(object):
    def setupUi(self, ploading):
        ploading.setObjectName("ploading")
        ploading.resize(281, 412)
        self.formLayoutWidget = QtGui.QWidget(ploading)
        self.formLayoutWidget.setGeometry(QtCore.QRect(30, 250, 221, 131))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtGui.QFormLayout(self.formLayoutWidget)
        self.formLayout.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.label = QtGui.QLabel(self.formLayoutWidget)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.label)
        self.itgaus = QtGui.QComboBox(self.formLayoutWidget)
        self.itgaus.setObjectName("itgaus")
        self.itgaus.addItem("")
        self.itgaus.addItem("")
        self.itgaus.addItem("")
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.itgaus)
        self.label_2 = QtGui.QLabel(self.formLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_2)
        self.itgamgaus = QtGui.QComboBox(self.formLayoutWidget)
        self.itgamgaus.setObjectName("itgamgaus")
        self.itgamgaus.addItem("")
        self.itgamgaus.addItem("")
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.itgamgaus)
        self.label_3 = QtGui.QLabel(self.formLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_3)
        self.iall = QtGui.QLineEdit(self.formLayoutWidget)
        self.iall.setObjectName("iall")
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.iall)
        self.label_4 = QtGui.QLabel(self.formLayoutWidget)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(3, QtGui.QFormLayout.LabelRole, self.label_4)
        self.label_5 = QtGui.QLabel(self.formLayoutWidget)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(4, QtGui.QFormLayout.LabelRole, self.label_5)
        self.ipspeed = QtGui.QLineEdit(self.formLayoutWidget)
        self.ipspeed.setObjectName("ipspeed")
        self.formLayout.setWidget(3, QtGui.QFormLayout.FieldRole, self.ipspeed)
        self.nbins = QtGui.QLineEdit(self.formLayoutWidget)
        self.nbins.setObjectName("nbins")
        self.formLayout.setWidget(4, QtGui.QFormLayout.FieldRole, self.nbins)
        self.tableWidget = QtGui.QTableWidget(ploading)
        self.tableWidget.setGeometry(QtCore.QRect(30, 30, 221, 211))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(1)
        self.tableWidget.setRowCount(6)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)

        self.retranslateUi(ploading)
        QtCore.QMetaObject.connectSlotsByName(ploading)

    def retranslateUi(self, ploading):
        ploading.setWindowTitle(QtGui.QApplication.translate("ploading", "Form", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("ploading", "Distribution Profile:", None, QtGui.QApplication.UnicodeUTF8))
        self.itgaus.setItemText(0, QtGui.QApplication.translate("ploading", "Gaussian", None, QtGui.QApplication.UnicodeUTF8))
        self.itgaus.setItemText(1, QtGui.QApplication.translate("ploading", "Uniform", None, QtGui.QApplication.UnicodeUTF8))
        self.itgaus.setItemText(2, QtGui.QApplication.translate("ploading", "Parabolic", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("ploading", "Energy Profile:", None, QtGui.QApplication.UnicodeUTF8))
        self.itgamgaus.setItemText(0, QtGui.QApplication.translate("ploading", "Gaussian", None, QtGui.QApplication.UnicodeUTF8))
        self.itgamgaus.setItemText(1, QtGui.QApplication.translate("ploading", "Uniform", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("ploading", "IALL:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("ploading", "IPSEED:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("ploading", "NBINS:", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget.verticalHeaderItem(0).setText(QtGui.QApplication.translate("ploading", "particle phase", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget.verticalHeaderItem(1).setText(QtGui.QApplication.translate("ploading", "energy distribution", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget.verticalHeaderItem(2).setText(QtGui.QApplication.translate("ploading", "x", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget.verticalHeaderItem(3).setText(QtGui.QApplication.translate("ploading", "y", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget.verticalHeaderItem(4).setText(QtGui.QApplication.translate("ploading", "px", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget.verticalHeaderItem(5).setText(QtGui.QApplication.translate("ploading", "py", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget.horizontalHeaderItem(0).setText(QtGui.QApplication.translate("ploading", "Hammersley Base", None, QtGui.QApplication.UnicodeUTF8))

class Ui_Mesh(object):
    def setupUi(self, Mesh):
        Mesh.setObjectName("Mesh")
        Mesh.resize(326, 331)
        self.formLayoutWidget = QtGui.QWidget(Mesh)
        self.formLayoutWidget.setGeometry(QtCore.QRect(30, 30, 261, 271))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtGui.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.label = QtGui.QLabel(self.formLayoutWidget)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.label)
        self.ncar = QtGui.QLineEdit(self.formLayoutWidget)
        self.ncar.setObjectName("ncar")
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.ncar)
        self.label_2 = QtGui.QLabel(self.formLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_2)
        self.lbc = QtGui.QPushButton(self.formLayoutWidget)
        self.lbc.setObjectName("lbc")
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.lbc)
        self.label_3 = QtGui.QLabel(self.formLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_3)
        self.rmax0 = QtGui.QLineEdit(self.formLayoutWidget)
        self.rmax0.setObjectName("rmax0")
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.rmax0)
        self.label_4 = QtGui.QLabel(self.formLayoutWidget)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(3, QtGui.QFormLayout.LabelRole, self.label_4)
        self.dgrid = QtGui.QLineEdit(self.formLayoutWidget)
        self.dgrid.setObjectName("dgrid")
        self.formLayout.setWidget(3, QtGui.QFormLayout.FieldRole, self.dgrid)
        self.label_5 = QtGui.QLabel(self.formLayoutWidget)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(4, QtGui.QFormLayout.LabelRole, self.label_5)
        self.nscz = QtGui.QSpinBox(self.formLayoutWidget)
        self.nscz.setObjectName("nscz")
        self.formLayout.setWidget(4, QtGui.QFormLayout.FieldRole, self.nscz)
        self.label_6 = QtGui.QLabel(self.formLayoutWidget)
        self.label_6.setObjectName("label_6")
        self.formLayout.setWidget(5, QtGui.QFormLayout.LabelRole, self.label_6)
        self.nscr = QtGui.QLineEdit(self.formLayoutWidget)
        self.nscr.setObjectName("nscr")
        self.formLayout.setWidget(5, QtGui.QFormLayout.FieldRole, self.nscr)
        self.label_7 = QtGui.QLabel(self.formLayoutWidget)
        self.label_7.setObjectName("label_7")
        self.formLayout.setWidget(6, QtGui.QFormLayout.LabelRole, self.label_7)
        self.nptr = QtGui.QLineEdit(self.formLayoutWidget)
        self.nptr.setObjectName("nptr")
        self.formLayout.setWidget(6, QtGui.QFormLayout.FieldRole, self.nptr)
        self.label_8 = QtGui.QLabel(self.formLayoutWidget)
        self.label_8.setObjectName("label_8")
        self.formLayout.setWidget(7, QtGui.QFormLayout.LabelRole, self.label_8)
        self.rmax0sc = QtGui.QLineEdit(self.formLayoutWidget)
        self.rmax0sc.setObjectName("rmax0sc")
        self.formLayout.setWidget(7, QtGui.QFormLayout.FieldRole, self.rmax0sc)
        self.label_9 = QtGui.QLabel(self.formLayoutWidget)
        self.label_9.setObjectName("label_9")
        self.formLayout.setWidget(8, QtGui.QFormLayout.LabelRole, self.label_9)
        self.iscrkup = QtGui.QPushButton(self.formLayoutWidget)
        self.iscrkup.setObjectName("iscrkup")
        self.formLayout.setWidget(8, QtGui.QFormLayout.FieldRole, self.iscrkup)

        self.retranslateUi(Mesh)
        QtCore.QMetaObject.connectSlotsByName(Mesh)

    def retranslateUi(self, Mesh):
        Mesh.setWindowTitle(QtGui.QApplication.translate("Mesh", "Form", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("Mesh", "Number of Grid Points:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("Mesh", "Boundary Condition:", None, QtGui.QApplication.UnicodeUTF8))
        self.lbc.setText(QtGui.QApplication.translate("Mesh", "Direchlet/Neumann", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("Mesh", "RMAX0:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("Mesh", "Grid Size:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("Mesh", "Number of Fourier Components:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("Mesh", "Number of Azimuthal Modes:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("Mesh", "Number of Radial Grid Points:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("Mesh", "RMAX0SC:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("Mesh", "Runge-Kutta:", None, QtGui.QApplication.UnicodeUTF8))
        self.iscrkup.setText(QtGui.QApplication.translate("Mesh", "Yes/No", None, QtGui.QApplication.UnicodeUTF8))

class Ui_timeparams(object):
    def setupUi(self, timeparams):
        timeparams.setObjectName("timeparams")
        timeparams.resize(271, 258)
        self.formLayoutWidget = QtGui.QWidget(timeparams)
        self.formLayoutWidget.setGeometry(QtCore.QRect(30, 30, 211, 211))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtGui.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.label = QtGui.QLabel(self.formLayoutWidget)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.label)
        self.itdp = QtGui.QPushButton(self.formLayoutWidget)
        self.itdp.setObjectName("itdp")
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.itdp)
        self.label_2 = QtGui.QLabel(self.formLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_2)
        self.curlen = QtGui.QLineEdit(self.formLayoutWidget)
        self.curlen.setObjectName("curlen")
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.curlen)
        self.label_3 = QtGui.QLabel(self.formLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_3)
        self.zsep = QtGui.QLineEdit(self.formLayoutWidget)
        self.zsep.setObjectName("zsep")
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.zsep)
        self.label_4 = QtGui.QLabel(self.formLayoutWidget)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(3, QtGui.QFormLayout.LabelRole, self.label_4)
        self.nslice = QtGui.QLineEdit(self.formLayoutWidget)
        self.nslice.setObjectName("nslice")
        self.formLayout.setWidget(3, QtGui.QFormLayout.FieldRole, self.nslice)
        self.label_5 = QtGui.QLabel(self.formLayoutWidget)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(4, QtGui.QFormLayout.LabelRole, self.label_5)
        self.ntail = QtGui.QLineEdit(self.formLayoutWidget)
        self.ntail.setObjectName("ntail")
        self.formLayout.setWidget(4, QtGui.QFormLayout.FieldRole, self.ntail)
        self.label_6 = QtGui.QLabel(self.formLayoutWidget)
        self.label_6.setObjectName("label_6")
        self.formLayout.setWidget(5, QtGui.QFormLayout.LabelRole, self.label_6)
        self.shotnoise = QtGui.QLineEdit(self.formLayoutWidget)
        self.shotnoise.setObjectName("shotnoise")
        self.formLayout.setWidget(5, QtGui.QFormLayout.FieldRole, self.shotnoise)
        self.label_7 = QtGui.QLabel(self.formLayoutWidget)
        self.label_7.setObjectName("label_7")
        self.formLayout.setWidget(6, QtGui.QFormLayout.LabelRole, self.label_7)
        self.isntyp = QtGui.QPushButton(self.formLayoutWidget)
        self.isntyp.setObjectName("isntyp")
        self.formLayout.setWidget(6, QtGui.QFormLayout.FieldRole, self.isntyp)

        self.retranslateUi(timeparams)
        QtCore.QMetaObject.connectSlotsByName(timeparams)

    def retranslateUi(self, timeparams):
        timeparams.setWindowTitle(QtGui.QApplication.translate("timeparams", "Form", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("timeparams", "Time Dependence:", None, QtGui.QApplication.UnicodeUTF8))
        self.itdp.setText(QtGui.QApplication.translate("timeparams", "Yes/No", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("timeparams", "Bunch Length:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("timeparams", "Slice Separation:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("timeparams", "Total Slices:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("timeparams", "Position of First Slice:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("timeparams", "Shotnoise:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("timeparams", "ISNTYP:", None, QtGui.QApplication.UnicodeUTF8))
        self.isntyp.setText(QtGui.QApplication.translate("timeparams", "Pennman/Fawley", None, QtGui.QApplication.UnicodeUTF8))

class Ui_simcon(object):
    def setupUi(self, simcon):
        simcon.setObjectName("simcon")
        simcon.resize(341, 249)
        self.formLayoutWidget = QtGui.QWidget(simcon)
        self.formLayoutWidget.setGeometry(QtCore.QRect(30, 30, 281, 191))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtGui.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.label = QtGui.QLabel(self.formLayoutWidget)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.label)
        self.delz = QtGui.QLineEdit(self.formLayoutWidget)
        self.delz.setObjectName("delz")
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.delz)
        self.label_2 = QtGui.QLabel(self.formLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_2)
        self.zstop = QtGui.QLineEdit(self.formLayoutWidget)
        self.zstop.setObjectName("zstop")
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.zstop)
        self.label_3 = QtGui.QLabel(self.formLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_3)
        self.iorb = QtGui.QPushButton(self.formLayoutWidget)
        self.iorb.setObjectName("iorb")
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.iorb)
        self.label_4 = QtGui.QLabel(self.formLayoutWidget)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(3, QtGui.QFormLayout.LabelRole, self.label_4)
        self.isravg = QtGui.QPushButton(self.formLayoutWidget)
        self.isravg.setObjectName("isravg")
        self.formLayout.setWidget(3, QtGui.QFormLayout.FieldRole, self.isravg)
        self.label_5 = QtGui.QLabel(self.formLayoutWidget)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(4, QtGui.QFormLayout.LabelRole, self.label_5)
        self.isrsig = QtGui.QPushButton(self.formLayoutWidget)
        self.isrsig.setObjectName("isrsig")
        self.formLayout.setWidget(4, QtGui.QFormLayout.FieldRole, self.isrsig)
        self.label_6 = QtGui.QLabel(self.formLayoutWidget)
        self.label_6.setObjectName("label_6")
        self.formLayout.setWidget(5, QtGui.QFormLayout.LabelRole, self.label_6)
        self.eloss = QtGui.QLineEdit(self.formLayoutWidget)
        self.eloss.setObjectName("eloss")
        self.formLayout.setWidget(5, QtGui.QFormLayout.FieldRole, self.eloss)

        self.retranslateUi(simcon)
        QtCore.QMetaObject.connectSlotsByName(simcon)

    def retranslateUi(self, simcon):
        simcon.setWindowTitle(QtGui.QApplication.translate("simcon", "Form", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("simcon", "Integration Step Size:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("simcon", "Integration Length:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("simcon", "Orbit Correction:", None, QtGui.QApplication.UnicodeUTF8))
        self.iorb.setText(QtGui.QApplication.translate("simcon", "Yes/No", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("simcon", "Include spontaneous synchrotron \n"
"energy loss:", None, QtGui.QApplication.UnicodeUTF8))
        self.isravg.setText(QtGui.QApplication.translate("simcon", "Yes/No", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("simcon", "Include energy spread from \n"
"quantum fluctuations", None, QtGui.QApplication.UnicodeUTF8))
        self.isrsig.setText(QtGui.QApplication.translate("simcon", "Yes/No", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("simcon", "Externally Applied energy loss:", None, QtGui.QApplication.UnicodeUTF8))

class Ui_scan(object):
    def setupUi(self, scan):
        scan.setObjectName("scan")
        scan.resize(313, 163)
        self.formLayoutWidget = QtGui.QWidget(scan)
        self.formLayoutWidget.setGeometry(QtCore.QRect(30, 30, 251, 101))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtGui.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.label = QtGui.QLabel(self.formLayoutWidget)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.label)
        self.comboBox = QtGui.QComboBox(self.formLayoutWidget)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.comboBox)
        self.label_2 = QtGui.QLabel(self.formLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_2)
        self.nscan = QtGui.QLineEdit(self.formLayoutWidget)
        self.nscan.setObjectName("nscan")
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.nscan)
        self.label_3 = QtGui.QLabel(self.formLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_3)
        self.svar = QtGui.QLineEdit(self.formLayoutWidget)
        self.svar.setObjectName("svar")
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.svar)

        self.retranslateUi(scan)
        QtCore.QMetaObject.connectSlotsByName(scan)

    def retranslateUi(self, scan):
        scan.setWindowTitle(QtGui.QApplication.translate("scan", "Form", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("scan", "Target Parameter to Scan:", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox.setItemText(0, QtGui.QApplication.translate("scan", "gamma0", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox.setItemText(1, QtGui.QApplication.translate("scan", "delgam", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox.setItemText(2, QtGui.QApplication.translate("scan", "curpeak", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox.setItemText(3, QtGui.QApplication.translate("scan", "xlamds", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox.setItemText(4, QtGui.QApplication.translate("scan", "aw0", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox.setItemText(5, QtGui.QApplication.translate("scan", "iseed", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox.setItemText(6, QtGui.QApplication.translate("scan", "pxbeam", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox.setItemText(7, QtGui.QApplication.translate("scan", "pybeam", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox.setItemText(8, QtGui.QApplication.translate("scan", "xbeam", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox.setItemText(9, QtGui.QApplication.translate("scan", "ybeam", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox.setItemText(10, QtGui.QApplication.translate("scan", "rxbeam", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox.setItemText(11, QtGui.QApplication.translate("scan", "rybeam", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox.setItemText(12, QtGui.QApplication.translate("scan", "xlamd", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox.setItemText(13, QtGui.QApplication.translate("scan", "delaw", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox.setItemText(14, QtGui.QApplication.translate("scan", "alphax", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox.setItemText(15, QtGui.QApplication.translate("scan", "alphay", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox.setItemText(16, QtGui.QApplication.translate("scan", "emitx", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox.setItemText(17, QtGui.QApplication.translate("scan", "emity", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox.setItemText(18, QtGui.QApplication.translate("scan", "prad0", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox.setItemText(19, QtGui.QApplication.translate("scan", "zrayl", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox.setItemText(20, QtGui.QApplication.translate("scan", "zwaist", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox.setItemText(21, QtGui.QApplication.translate("scan", "awd", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox.setItemText(22, QtGui.QApplication.translate("scan", "beamfile", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox.setItemText(23, QtGui.QApplication.translate("scan", "beamopt", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox.setItemText(24, QtGui.QApplication.translate("scan", "beamgam", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("scan", "Steps per Scan:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("scan", "Scan Range:", None, QtGui.QApplication.UnicodeUTF8))

class Ui_io(object):
    def setupUi(self, io):
        io.setObjectName("io")
        io.resize(401, 921)
        self.formLayoutWidget = QtGui.QWidget(io)
        self.formLayoutWidget.setGeometry(QtCore.QRect(30, 30, 343, 791))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtGui.QFormLayout(self.formLayoutWidget)
        self.formLayout.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.label = QtGui.QLabel(self.formLayoutWidget)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.label)
        self.iphsty = QtGui.QPushButton(self.formLayoutWidget)
        self.iphsty.setObjectName("iphsty")
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.iphsty)
        self.label_2 = QtGui.QLabel(self.formLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_2)
        self.ishsty = QtGui.QPushButton(self.formLayoutWidget)
        self.ishsty.setObjectName("ishsty")
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.ishsty)
        self.label_3 = QtGui.QLabel(self.formLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_3)
        self.ippart = QtGui.QPushButton(self.formLayoutWidget)
        self.ippart.setObjectName("ippart")
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.ippart)
        self.label_4 = QtGui.QLabel(self.formLayoutWidget)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(3, QtGui.QFormLayout.LabelRole, self.label_4)
        self.ispart = QtGui.QPushButton(self.formLayoutWidget)
        self.ispart.setObjectName("ispart")
        self.formLayout.setWidget(3, QtGui.QFormLayout.FieldRole, self.ispart)
        self.label_5 = QtGui.QLabel(self.formLayoutWidget)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(4, QtGui.QFormLayout.LabelRole, self.label_5)
        self.ipradi = QtGui.QPushButton(self.formLayoutWidget)
        self.ipradi.setObjectName("ipradi")
        self.formLayout.setWidget(4, QtGui.QFormLayout.FieldRole, self.ipradi)
        self.label_6 = QtGui.QLabel(self.formLayoutWidget)
        self.label_6.setObjectName("label_6")
        self.formLayout.setWidget(5, QtGui.QFormLayout.LabelRole, self.label_6)
        self.isradi = QtGui.QPushButton(self.formLayoutWidget)
        self.isradi.setObjectName("isradi")
        self.formLayout.setWidget(5, QtGui.QFormLayout.FieldRole, self.isradi)
        self.label_7 = QtGui.QLabel(self.formLayoutWidget)
        self.label_7.setObjectName("label_7")
        self.formLayout.setWidget(6, QtGui.QFormLayout.LabelRole, self.label_7)
        self.iotail = QtGui.QPushButton(self.formLayoutWidget)
        self.iotail.setObjectName("iotail")
        self.formLayout.setWidget(6, QtGui.QFormLayout.FieldRole, self.iotail)
        self.label_8 = QtGui.QLabel(self.formLayoutWidget)
        self.label_8.setObjectName("label_8")
        self.formLayout.setWidget(7, QtGui.QFormLayout.LabelRole, self.label_8)
        self.outputfile = QtGui.QPushButton(self.formLayoutWidget)
        self.outputfile.setObjectName("outputfile")
        self.formLayout.setWidget(7, QtGui.QFormLayout.FieldRole, self.outputfile)
        self.label_9 = QtGui.QLabel(self.formLayoutWidget)
        self.label_9.setObjectName("label_9")
        self.formLayout.setWidget(8, QtGui.QFormLayout.LabelRole, self.label_9)
        self.magin = QtGui.QPushButton(self.formLayoutWidget)
        self.magin.setObjectName("magin")
        self.formLayout.setWidget(8, QtGui.QFormLayout.FieldRole, self.magin)
        self.label_10 = QtGui.QLabel(self.formLayoutWidget)
        self.label_10.setObjectName("label_10")
        self.formLayout.setWidget(9, QtGui.QFormLayout.LabelRole, self.label_10)
        self.magout = QtGui.QPushButton(self.formLayoutWidget)
        self.magout.setObjectName("magout")
        self.formLayout.setWidget(9, QtGui.QFormLayout.FieldRole, self.magout)
        self.label_11 = QtGui.QLabel(self.formLayoutWidget)
        self.label_11.setObjectName("label_11")
        self.formLayout.setWidget(10, QtGui.QFormLayout.LabelRole, self.label_11)
        self.dump = QtGui.QComboBox(self.formLayoutWidget)
        self.dump.setObjectName("dump")
        self.dump.addItem("")
        self.dump.addItem("")
        self.dump.addItem("")
        self.formLayout.setWidget(10, QtGui.QFormLayout.FieldRole, self.dump)
        self.label_12 = QtGui.QLabel(self.formLayoutWidget)
        self.label_12.setObjectName("label_12")
        self.formLayout.setWidget(11, QtGui.QFormLayout.LabelRole, self.label_12)
        self.beamfile = QtGui.QPushButton(self.formLayoutWidget)
        self.beamfile.setObjectName("beamfile")
        self.formLayout.setWidget(11, QtGui.QFormLayout.FieldRole, self.beamfile)
        self.label_13 = QtGui.QLabel(self.formLayoutWidget)
        self.label_13.setObjectName("label_13")
        self.formLayout.setWidget(12, QtGui.QFormLayout.LabelRole, self.label_13)
        self.radfile = QtGui.QPushButton(self.formLayoutWidget)
        self.radfile.setObjectName("radfile")
        self.formLayout.setWidget(12, QtGui.QFormLayout.FieldRole, self.radfile)
        self.label_14 = QtGui.QLabel(self.formLayoutWidget)
        self.label_14.setObjectName("label_14")
        self.formLayout.setWidget(13, QtGui.QFormLayout.LabelRole, self.label_14)
        self.distfile = QtGui.QPushButton(self.formLayoutWidget)
        self.distfile.setObjectName("distfile")
        self.formLayout.setWidget(13, QtGui.QFormLayout.FieldRole, self.distfile)
        self.label_15 = QtGui.QLabel(self.formLayoutWidget)
        self.label_15.setObjectName("label_15")
        self.formLayout.setWidget(14, QtGui.QFormLayout.LabelRole, self.label_15)
        self.ndcut = QtGui.QPushButton(self.formLayoutWidget)
        self.ndcut.setObjectName("ndcut")
        self.formLayout.setWidget(14, QtGui.QFormLayout.FieldRole, self.ndcut)
        self.label_16 = QtGui.QLabel(self.formLayoutWidget)
        self.label_16.setObjectName("label_16")
        self.formLayout.setWidget(15, QtGui.QFormLayout.LabelRole, self.label_16)
        self.fieldfile = QtGui.QPushButton(self.formLayoutWidget)
        self.fieldfile.setObjectName("fieldfile")
        self.formLayout.setWidget(15, QtGui.QFormLayout.FieldRole, self.fieldfile)
        self.label_17 = QtGui.QLabel(self.formLayoutWidget)
        self.label_17.setObjectName("label_17")
        self.formLayout.setWidget(16, QtGui.QFormLayout.LabelRole, self.label_17)
        self.aligngradf = QtGui.QPushButton(self.formLayoutWidget)
        self.aligngradf.setObjectName("aligngradf")
        self.formLayout.setWidget(16, QtGui.QFormLayout.FieldRole, self.aligngradf)
        self.label_18 = QtGui.QLabel(self.formLayoutWidget)
        self.label_18.setObjectName("label_18")
        self.formLayout.setWidget(17, QtGui.QFormLayout.LabelRole, self.label_18)
        self.offsetradf = QtGui.QLineEdit(self.formLayoutWidget)
        self.offsetradf.setObjectName("offsetradf")
        self.formLayout.setWidget(17, QtGui.QFormLayout.FieldRole, self.offsetradf)
        self.label_19 = QtGui.QLabel(self.formLayoutWidget)
        self.label_19.setObjectName("label_19")
        self.formLayout.setWidget(18, QtGui.QFormLayout.LabelRole, self.label_19)
        self.partfile = QtGui.QPushButton(self.formLayoutWidget)
        self.partfile.setObjectName("partfile")
        self.formLayout.setWidget(18, QtGui.QFormLayout.FieldRole, self.partfile)
        self.label_20 = QtGui.QLabel(self.formLayoutWidget)
        self.label_20.setObjectName("label_20")
        self.formLayout.setWidget(19, QtGui.QFormLayout.LabelRole, self.label_20)
        self.convharm = QtGui.QLineEdit(self.formLayoutWidget)
        self.convharm.setObjectName("convharm")
        self.formLayout.setWidget(19, QtGui.QFormLayout.FieldRole, self.convharm)
        self.label_21 = QtGui.QLabel(self.formLayoutWidget)
        self.label_21.setObjectName("label_21")
        self.formLayout.setWidget(20, QtGui.QFormLayout.LabelRole, self.label_21)
        self.multiconv = QtGui.QLineEdit(self.formLayoutWidget)
        self.multiconv.setObjectName("multiconv")
        self.formLayout.setWidget(20, QtGui.QFormLayout.FieldRole, self.multiconv)
        self.label_22 = QtGui.QLabel(self.formLayoutWidget)
        self.label_22.setObjectName("label_22")
        self.formLayout.setWidget(21, QtGui.QFormLayout.LabelRole, self.label_22)
        self.ibfield = QtGui.QLineEdit(self.formLayoutWidget)
        self.ibfield.setObjectName("ibfield")
        self.formLayout.setWidget(21, QtGui.QFormLayout.FieldRole, self.ibfield)
        self.label_23 = QtGui.QLabel(self.formLayoutWidget)
        self.label_23.setObjectName("label_23")
        self.formLayout.setWidget(22, QtGui.QFormLayout.LabelRole, self.label_23)
        self.imagl = QtGui.QLineEdit(self.formLayoutWidget)
        self.imagl.setObjectName("imagl")
        self.formLayout.setWidget(22, QtGui.QFormLayout.FieldRole, self.imagl)
        self.label_24 = QtGui.QLabel(self.formLayoutWidget)
        self.label_24.setObjectName("label_24")
        self.formLayout.setWidget(23, QtGui.QFormLayout.LabelRole, self.label_24)
        self.idril = QtGui.QLineEdit(self.formLayoutWidget)
        self.idril.setObjectName("idril")
        self.formLayout.setWidget(23, QtGui.QFormLayout.FieldRole, self.idril)
        self.label_25 = QtGui.QLabel(self.formLayoutWidget)
        self.label_25.setObjectName("label_25")
        self.formLayout.setWidget(24, QtGui.QFormLayout.LabelRole, self.label_25)
        self.trama = QtGui.QPushButton(self.formLayoutWidget)
        self.trama.setObjectName("trama")
        self.formLayout.setWidget(24, QtGui.QFormLayout.FieldRole, self.trama)
        self.label_26 = QtGui.QLabel(self.formLayoutWidget)
        self.label_26.setObjectName("label_26")
        self.formLayout.setWidget(25, QtGui.QFormLayout.LabelRole, self.label_26)
        self.ilog = QtGui.QPushButton(self.formLayoutWidget)
        self.ilog.setObjectName("ilog")
        self.formLayout.setWidget(25, QtGui.QFormLayout.FieldRole, self.ilog)
        self.label_27 = QtGui.QLabel(self.formLayoutWidget)
        self.label_27.setObjectName("label_27")
        self.formLayout.setWidget(26, QtGui.QFormLayout.LabelRole, self.label_27)
        self.ffspec = QtGui.QLineEdit(self.formLayoutWidget)
        self.ffspec.setObjectName("ffspec")
        self.formLayout.setWidget(26, QtGui.QFormLayout.FieldRole, self.ffspec)

        self.retranslateUi(io)
        QtCore.QMetaObject.connectSlotsByName(io)

    def retranslateUi(self, io):
        io.setWindowTitle(QtGui.QApplication.translate("io", "Form", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("io", "Output at each integration step:", None, QtGui.QApplication.UnicodeUTF8))
        self.iphsty.setText(QtGui.QApplication.translate("io", "Yes/No", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("io", "Output at each Slice:", None, QtGui.QApplication.UnicodeUTF8))
        self.ishsty.setText(QtGui.QApplication.translate("io", "Yes/No", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("io", "Output Particle Distribution at \n"
"each integration step", None, QtGui.QApplication.UnicodeUTF8))
        self.ippart.setText(QtGui.QApplication.translate("io", "Yes/No", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("io", "Output Particle Distribution at\n"
"each slice:", None, QtGui.QApplication.UnicodeUTF8))
        self.ispart.setText(QtGui.QApplication.translate("io", "Yes/No", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("io", "Output Field Distribution at \n"
"each integration step:", None, QtGui.QApplication.UnicodeUTF8))
        self.ipradi.setText(QtGui.QApplication.translate("io", "Yes/No", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("io", "Output Field Distribution at\n"
"each slice:", None, QtGui.QApplication.UnicodeUTF8))
        self.isradi.setText(QtGui.QApplication.translate("io", "Yes/No", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("io", "IOTAIL:", None, QtGui.QApplication.UnicodeUTF8))
        self.iotail.setText(QtGui.QApplication.translate("io", "Yes/No", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("io", "Output File:", None, QtGui.QApplication.UnicodeUTF8))
        self.outputfile.setText(QtGui.QApplication.translate("io", "Export", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("io", "Magnetic Field Input:", None, QtGui.QApplication.UnicodeUTF8))
        self.magin.setText(QtGui.QApplication.translate("io", "Import", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("io", "Magnetic Field Output:", None, QtGui.QApplication.UnicodeUTF8))
        self.magout.setText(QtGui.QApplication.translate("io", "Import", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("io", "DUMP:", None, QtGui.QApplication.UnicodeUTF8))
        self.dump.setItemText(0, QtGui.QApplication.translate("io", "Field", None, QtGui.QApplication.UnicodeUTF8))
        self.dump.setItemText(1, QtGui.QApplication.translate("io", "Distribution", None, QtGui.QApplication.UnicodeUTF8))
        self.dump.setItemText(2, QtGui.QApplication.translate("io", "Field & Distribuition", None, QtGui.QApplication.UnicodeUTF8))
        self.label_12.setText(QtGui.QApplication.translate("io", "Beam Input File:", None, QtGui.QApplication.UnicodeUTF8))
        self.beamfile.setText(QtGui.QApplication.translate("io", "Import", None, QtGui.QApplication.UnicodeUTF8))
        self.label_13.setText(QtGui.QApplication.translate("io", "Seeding Radiation Input:", None, QtGui.QApplication.UnicodeUTF8))
        self.radfile.setText(QtGui.QApplication.translate("io", "Import", None, QtGui.QApplication.UnicodeUTF8))
        self.label_14.setText(QtGui.QApplication.translate("io", "6D Phase Space:", None, QtGui.QApplication.UnicodeUTF8))
        self.distfile.setText(QtGui.QApplication.translate("io", "Import", None, QtGui.QApplication.UnicodeUTF8))
        self.label_15.setText(QtGui.QApplication.translate("io", "NDCUT:", None, QtGui.QApplication.UnicodeUTF8))
        self.ndcut.setText(QtGui.QApplication.translate("io", "PushButton", None, QtGui.QApplication.UnicodeUTF8))
        self.label_16.setText(QtGui.QApplication.translate("io", "Field File:", None, QtGui.QApplication.UnicodeUTF8))
        self.fieldfile.setText(QtGui.QApplication.translate("io", "Export", None, QtGui.QApplication.UnicodeUTF8))
        self.label_17.setText(QtGui.QApplication.translate("io", "Align Radiation Field:", None, QtGui.QApplication.UnicodeUTF8))
        self.aligngradf.setText(QtGui.QApplication.translate("io", "Yes/No", None, QtGui.QApplication.UnicodeUTF8))
        self.label_18.setText(QtGui.QApplication.translate("io", "Offset Radiation:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_19.setText(QtGui.QApplication.translate("io", "PARTFILE:", None, QtGui.QApplication.UnicodeUTF8))
        self.partfile.setText(QtGui.QApplication.translate("io", "Import", None, QtGui.QApplication.UnicodeUTF8))
        self.label_20.setText(QtGui.QApplication.translate("io", "CONVHARM:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_21.setText(QtGui.QApplication.translate("io", "MULTICONV:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_22.setText(QtGui.QApplication.translate("io", "IBFIELD:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_23.setText(QtGui.QApplication.translate("io", "IMAGL:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_24.setText(QtGui.QApplication.translate("io", "IDRIL:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_25.setText(QtGui.QApplication.translate("io", "Transport Matrix:", None, QtGui.QApplication.UnicodeUTF8))
        self.trama.setText(QtGui.QApplication.translate("io", "define matrix", None, QtGui.QApplication.UnicodeUTF8))
        self.label_26.setText(QtGui.QApplication.translate("io", "Log:", None, QtGui.QApplication.UnicodeUTF8))
        self.ilog.setText(QtGui.QApplication.translate("io", "Yes/No", None, QtGui.QApplication.UnicodeUTF8))
        self.label_27.setText(QtGui.QApplication.translate("io", "FFSPEC:", None, QtGui.QApplication.UnicodeUTF8))
        

class makeund(QtGui.QWidget):
    def __init__(self):
        QtGui.QWidget.__init__(self)
        self.ui = Ui_genund()
        self.ui.setupUi(self)
        self.ui.aw0.setText('2.4749')
        self.ui.iwityp.setCheckable(True)
        self.ui.iwityp.setChecked(False)
        #self.ui.xkx.setText('0')
        #self.ui.xky.setText('1')
        self.ui.xlamd.setText('0.03')
        self.ui.nwig.setText('144')
        self.ui.nsec.setText('30')
        self.ui.delaw.setText('0')
        self.ui.awx.setText('0')
        self.ui.awy.setText('0')
        self.ui.seed.setText('20')
        self.ui.iertyp.setRange(-2,2)
        

class makefodo(QtGui.QWidget):
    def __init__(self):
        QtGui.QWidget.__init__(self)
        self.ui = Ui_genfodo()
        self.ui.setupUi(self)
        self.ui.quadf.setText('12.7')
        self.ui.quadd.setText('12.7')
        self.ui.fl.setText('8.0')
        self.ui.dl.setText('8.0')
        self.ui.drl.setText('112')
        self.ui.f1st.setText('0')
        self.ui.qfdx.setText('0')
        self.ui.qfdy.setText('0')
        self.ui.solen.setText('0')
        self.ui.sl.setText('0')        
        

class makebeam(QtGui.QWidget):
    def __init__(self):
        QtGui.QWidget.__init__(self)
        self.ui = Ui_genbeam()
        self.ui.setupUi(self)
        self.ui.gamma0.setText('26700')
        self.ui.delgam.setText('2.8')
        self.ui.rxbeam.setText('34.71e-6')
        self.ui.rybeam.setText('28.63e-6')
        self.ui.alphax.setText('1.2268')
        self.ui.alphay.setText('-0.8375')
        self.ui.emitx.setText('1.2e-6')
        self.ui.emity.setText('1.2e-6')
        self.ui.xbeam.setText('0')
        self.ui.ybeam.setText('0')
        self.ui.pxbeam.setText('0')
        self.ui.pybeam.setText('0')
        self.ui.curpeak.setText('250')
        

class makerad(QtGui.QWidget):
    def __init__(self):
        QtGui.QWidget.__init__(self)
        self.ui = Ui_radiation()
        self.ui.setupUi(self)
        self.ui.xlamds.setText('1.50e-10')
        self.ui.prad0.setText('3000')
        self.ui.zrayl.setText('50')
        self.ui.zwaist.setText('0')
        self.ui.iallharm.setCheckable(True)
        self.ui.iallharm.setChecked(False)
        self.ui.nharm.setText('1')
        self.ui.iharmsc.setCheckable(True)
        self.ui.iharmsc.setChecked(False)
        self.ui.pradh0.setText('0')   
        

class makepload(QtGui.QWidget):
    def __init__(self):
        QtGui.QWidget.__init__(self)
        self.ui = Ui_ploading()
        self.ui.setupUi(self)
        self.ui.tableWidget.setItem(0,0,QtGui.QTableWidgetItem('7'))
        self.ui.tableWidget.setItem(1,0,QtGui.QTableWidgetItem('5'))
        self.ui.tableWidget.setItem(2,0,QtGui.QTableWidgetItem('1'))
        self.ui.tableWidget.setItem(3,0,QtGui.QTableWidgetItem('2'))
        self.ui.tableWidget.setItem(4,0,QtGui.QTableWidgetItem('3'))
        self.ui.tableWidget.setItem(5,0,QtGui.QTableWidgetItem('4'))
        #self.ui.itgaus.setCurrentIndex(0)
        self.ui.itgamgaus.setCurrentIndex((1))
        self.ui.iall.setText('0')
        self.ui.ipspeed.setText('-1')
        self.ui.nbins.setText('4') 
        

class makemesh(QtGui.QWidget):
    def __init__(self):
        QtGui.QWidget.__init__(self)
        self.ui = Ui_Mesh()
        self.ui.setupUi(self)
        self.ui.ncar.setText('139')
        self.ui.lbc.setCheckable(True)
        self.ui.lbc.setChecked(False)
        self.ui.rmax0.setText('11')
        self.ui.dgrid.setText('0')
        #self.ui.nscz.setRange(0,10)
        self.ui.nscr.setText('1')
        self.ui.nptr.setText('40')
        self.ui.rmax0sc.setText('0')
        self.ui.iscrkup.setCheckable(True)
        self.ui.iscrkup.setChecked(False)
        

class maketime(QtGui.QWidget):
    def __init__(self):
        QtGui.QWidget.__init__(self)
        self.ui = Ui_timeparams()
        self.ui.setupUi(self)
        self.ui.itdp.setCheckable(True)
        self.ui.itdp.setChecked(False)
        self.ui.curlen.setText('1.0e-3')
        self.ui.zsep.setText('32')
        self.ui.nslice.setText('13302')
        self.ui.ntail.setText('25')
        self.ui.shotnoise.setText('1')
        self.ui.isntyp.setCheckable(True)
        self.ui.isntyp.setChecked(False)
        

class makesim(QtGui.QWidget):
    def __init__(self):
        QtGui.QWidget.__init__(self)
        self.ui = Ui_simcon()
        self.ui.setupUi(self)
        self.ui.delz.setText('8')
        self.ui.zstop.setText('132')
        self.ui.iorb.setCheckable(True)
        self.ui.isravg.setCheckable(True)
        self.ui.isrsig.setCheckable(True)
        self.ui.iorb.setChecked(False)
        self.ui.isravg.setChecked(False)
        self.ui.isrsig.setChecked(True)
        self.ui.eloss.setText('0')

class makescan(QtGui.QWidget):
    def __init__(self):
        QtGui.QWidget.__init__(self)
        self.ui = Ui_scan()
        self.ui.setupUi(self)
        #self.ui.iscan.setCurrentIndex(0)
        self.ui.nscan.setText('3')
        self.ui.svar.setText('0.01')

class makeio(QtGui.QWidget):
    def __init__(self):
        QtGui.QWidget.__init__(self)
        self.ui = Ui_io()
        self.ui.setupUi(self)
        self.ui.iphsty.setCheckable(True)
        self.ui.ishsty.setCheckable(True)
        self.ui.ippart.setCheckable(True)
        self.ui.ispart.setCheckable(True)
        self.ui.ipradi.setCheckable(True)
        self.ui.isradi.setCheckable(True)
        self.ui.iotail.setCheckable(True)
        self.ui.ndcut.setCheckable(True)
        self.ui.aligngradf.setCheckable(True)
        self.ui.ilog.setCheckable(True)
        self.ui.trama.setCheckable(True)
        self.ui.iphsty.setChecked(True)
        self.ui.ishsty.setChecked(True)
        self.ui.ippart.setChecked(False)
        self.ui.ispart.setChecked(True)
        self.ui.ipradi.setChecked(False)
        self.ui.isradi.setChecked(False)
        self.ui.iotail.setChecked(True)
        self.ui.ndcut.setChecked(False)
        self.ui.aligngradf.setChecked(False)
        self.ui.ilog.setChecked(False)
        self.ui.trama.setChecked(False)

        #outputfile = 'lcls.out'
        #maginfile = 'lcls.lat'
        self.ui.dump.setCurrentIndex(0)
        #idmpfld=1
        #distfile='lcls_resonant.dist'
        self.ui.offsetradf.setText('0')
        self.ui.convharm.setText('1')
        self.ui.multiconv.setText('0')
        self.ui.ibfield.setText('0')
        self.ui.imagl.setText('0')
        self.ui.idril.setText('0')
        #LOUT=1 1 1 1 1 0 1 1 1 1 1 1 1 1 1 0 0 0 0 1 0 0
        self.ui.ffspec.setText('0')
        

        

        
        
