# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'radtrack/ui/BunchInterface.ui'
#
# Created: Thu Feb  4 09:02:00 2016
#      by: PyQt4 UI code generator 4.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_bunchInterface(object):
    def setupUi(self, bunchInterface):
        bunchInterface.setObjectName(_fromUtf8("bunchInterface"))
        bunchInterface.resize(368, 620)
        self.horizontalLayout = QtGui.QHBoxLayout(bunchInterface)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.distribType = QtGui.QToolButton(bunchInterface)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.distribType.sizePolicy().hasHeightForWidth())
        self.distribType.setSizePolicy(sizePolicy)
        self.distribType.setMinimumSize(QtCore.QSize(0, 23))
        self.distribType.setObjectName(_fromUtf8("distribType"))
        self.gridLayout_2.addWidget(self.distribType, 0, 0, 1, 1)
        self.noTitles = QtGui.QToolButton(bunchInterface)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.noTitles.sizePolicy().hasHeightForWidth())
        self.noTitles.setSizePolicy(sizePolicy)
        self.noTitles.setMinimumSize(QtCore.QSize(0, 23))
        self.noTitles.setToolTip(_fromUtf8(""))
        self.noTitles.setStatusTip(_fromUtf8(""))
        self.noTitles.setPopupMode(QtGui.QToolButton.InstantPopup)
        self.noTitles.setObjectName(_fromUtf8("noTitles"))
        self.gridLayout_2.addWidget(self.noTitles, 0, 2, 1, 1)
        self.plotType = QtGui.QToolButton(bunchInterface)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.plotType.sizePolicy().hasHeightForWidth())
        self.plotType.setSizePolicy(sizePolicy)
        self.plotType.setMinimumSize(QtCore.QSize(0, 23))
        self.plotType.setToolTip(_fromUtf8(""))
        self.plotType.setObjectName(_fromUtf8("plotType"))
        self.gridLayout_2.addWidget(self.plotType, 0, 1, 1, 1)
        self.generateBunch = QtGui.QPushButton(bunchInterface)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.generateBunch.sizePolicy().hasHeightForWidth())
        self.generateBunch.setSizePolicy(sizePolicy)
        self.generateBunch.setMinimumSize(QtCore.QSize(0, 23))
        self.generateBunch.setFocusPolicy(QtCore.Qt.TabFocus)
        self.generateBunch.setToolTip(_fromUtf8(""))
        self.generateBunch.setObjectName(_fromUtf8("generateBunch"))
        self.gridLayout_2.addWidget(self.generateBunch, 2, 1, 1, 1)
        self.axisType = QtGui.QToolButton(bunchInterface)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.axisType.sizePolicy().hasHeightForWidth())
        self.axisType.setSizePolicy(sizePolicy)
        self.axisType.setMinimumSize(QtCore.QSize(0, 23))
        self.axisType.setToolTip(_fromUtf8(""))
        self.axisType.setObjectName(_fromUtf8("axisType"))
        self.gridLayout_2.addWidget(self.axisType, 1, 1, 1, 1)
        self.aspectRatio = QtGui.QToolButton(bunchInterface)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.aspectRatio.sizePolicy().hasHeightForWidth())
        self.aspectRatio.setSizePolicy(sizePolicy)
        self.aspectRatio.setMinimumSize(QtCore.QSize(0, 23))
        self.aspectRatio.setPopupMode(QtGui.QToolButton.InstantPopup)
        self.aspectRatio.setObjectName(_fromUtf8("aspectRatio"))
        self.gridLayout_2.addWidget(self.aspectRatio, 1, 2, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_2)
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.highLevelInputsLabel = QtGui.QLabel(bunchInterface)
        self.highLevelInputsLabel.setObjectName(_fromUtf8("highLevelInputsLabel"))
        self.gridLayout.addWidget(self.highLevelInputsLabel, 0, 0, 1, 1)
        self.unitsLabel = QtGui.QLabel(bunchInterface)
        self.unitsLabel.setObjectName(_fromUtf8("unitsLabel"))
        self.gridLayout.addWidget(self.unitsLabel, 0, 2, 1, 2)
        self.numPtclsLabel = QtGui.QLabel(bunchInterface)
        self.numPtclsLabel.setObjectName(_fromUtf8("numPtclsLabel"))
        self.gridLayout.addWidget(self.numPtclsLabel, 1, 0, 1, 1)
        self.numPtcls = QtGui.QLineEdit(bunchInterface)
        self.numPtcls.setToolTip(_fromUtf8(""))
        self.numPtcls.setObjectName(_fromUtf8("numPtcls"))
        self.gridLayout.addWidget(self.numPtcls, 1, 1, 1, 1)
        self.unitsPosLabel = QtGui.QLabel(bunchInterface)
        self.unitsPosLabel.setObjectName(_fromUtf8("unitsPosLabel"))
        self.gridLayout.addWidget(self.unitsPosLabel, 1, 2, 1, 1)
        self.unitsPos = QtGui.QLineEdit(bunchInterface)
        self.unitsPos.setObjectName(_fromUtf8("unitsPos"))
        self.gridLayout.addWidget(self.unitsPos, 1, 3, 1, 1)
        self.designMomentumLabel = QtGui.QLabel(bunchInterface)
        self.designMomentumLabel.setObjectName(_fromUtf8("designMomentumLabel"))
        self.gridLayout.addWidget(self.designMomentumLabel, 2, 0, 1, 1)
        self.designMomentum = QtGui.QLineEdit(bunchInterface)
        self.designMomentum.setObjectName(_fromUtf8("designMomentum"))
        self.gridLayout.addWidget(self.designMomentum, 2, 1, 1, 1)
        self.unitsAngleLabel = QtGui.QLabel(bunchInterface)
        self.unitsAngleLabel.setObjectName(_fromUtf8("unitsAngleLabel"))
        self.gridLayout.addWidget(self.unitsAngleLabel, 2, 2, 1, 1)
        self.unitsAngle = QtGui.QLineEdit(bunchInterface)
        self.unitsAngle.setDragEnabled(True)
        self.unitsAngle.setObjectName(_fromUtf8("unitsAngle"))
        self.gridLayout.addWidget(self.unitsAngle, 2, 3, 1, 1)
        self.charge = QtGui.QLabel(bunchInterface)
        self.charge.setObjectName(_fromUtf8("charge"))
        self.gridLayout.addWidget(self.charge, 3, 0, 1, 1)
        self.totalCharge = QtGui.QLineEdit(bunchInterface)
        self.totalCharge.setToolTip(_fromUtf8(""))
        self.totalCharge.setObjectName(_fromUtf8("totalCharge"))
        self.gridLayout.addWidget(self.totalCharge, 3, 1, 1, 1)
        self.ticksLabel = QtGui.QLabel(bunchInterface)
        self.ticksLabel.setObjectName(_fromUtf8("ticksLabel"))
        self.gridLayout.addWidget(self.ticksLabel, 3, 2, 1, 1)
        self.numTicks = QtGui.QLineEdit(bunchInterface)
        self.numTicks.setObjectName(_fromUtf8("numTicks"))
        self.gridLayout.addWidget(self.numTicks, 3, 3, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.perpTwissLabel = QtGui.QLabel(bunchInterface)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.perpTwissLabel.sizePolicy().hasHeightForWidth())
        self.perpTwissLabel.setSizePolicy(sizePolicy)
        self.perpTwissLabel.setObjectName(_fromUtf8("perpTwissLabel"))
        self.horizontalLayout_2.addWidget(self.perpTwissLabel)
        self.perpTwissSpec = QtGui.QToolButton(bunchInterface)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.perpTwissSpec.sizePolicy().hasHeightForWidth())
        self.perpTwissSpec.setSizePolicy(sizePolicy)
        self.perpTwissSpec.setMinimumSize(QtCore.QSize(125, 0))
        self.perpTwissSpec.setMaximumSize(QtCore.QSize(125, 16777215))
        self.perpTwissSpec.setObjectName(_fromUtf8("perpTwissSpec"))
        self.horizontalLayout_2.addWidget(self.perpTwissSpec)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.twissTable = QtGui.QTableWidget(bunchInterface)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.twissTable.sizePolicy().hasHeightForWidth())
        self.twissTable.setSizePolicy(sizePolicy)
        self.twissTable.setToolTip(_fromUtf8(""))
        self.twissTable.setObjectName(_fromUtf8("twissTable"))
        self.twissTable.setColumnCount(3)
        self.twissTable.setRowCount(2)
        item = QtGui.QTableWidgetItem()
        self.twissTable.setVerticalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.twissTable.setVerticalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.twissTable.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.twissTable.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.twissTable.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.twissTable.setItem(0, 0, item)
        self.verticalLayout.addWidget(self.twissTable)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.longTwissLabel = QtGui.QLabel(bunchInterface)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.longTwissLabel.sizePolicy().hasHeightForWidth())
        self.longTwissLabel.setSizePolicy(sizePolicy)
        self.longTwissLabel.setObjectName(_fromUtf8("longTwissLabel"))
        self.horizontalLayout_3.addWidget(self.longTwissLabel)
        self.longTwissSpec = QtGui.QToolButton(bunchInterface)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.longTwissSpec.sizePolicy().hasHeightForWidth())
        self.longTwissSpec.setSizePolicy(sizePolicy)
        self.longTwissSpec.setMinimumSize(QtCore.QSize(125, 0))
        self.longTwissSpec.setMaximumSize(QtCore.QSize(125, 16777215))
        self.longTwissSpec.setObjectName(_fromUtf8("longTwissSpec"))
        self.horizontalLayout_3.addWidget(self.longTwissSpec)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.twissTableZ = QtGui.QTableWidget(bunchInterface)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.twissTableZ.sizePolicy().hasHeightForWidth())
        self.twissTableZ.setSizePolicy(sizePolicy)
        self.twissTableZ.setToolTip(_fromUtf8(""))
        self.twissTableZ.setObjectName(_fromUtf8("twissTableZ"))
        self.twissTableZ.setColumnCount(3)
        self.twissTableZ.setRowCount(1)
        item = QtGui.QTableWidgetItem()
        self.twissTableZ.setVerticalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.twissTableZ.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.twissTableZ.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.twissTableZ.setHorizontalHeaderItem(2, item)
        self.verticalLayout.addWidget(self.twissTableZ)
        self.offsetLabel = QtGui.QLabel(bunchInterface)
        self.offsetLabel.setObjectName(_fromUtf8("offsetLabel"))
        self.verticalLayout.addWidget(self.offsetLabel)
        self.offsetTable = QtGui.QTableWidget(bunchInterface)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.offsetTable.sizePolicy().hasHeightForWidth())
        self.offsetTable.setSizePolicy(sizePolicy)
        self.offsetTable.setToolTip(_fromUtf8(""))
        self.offsetTable.setObjectName(_fromUtf8("offsetTable"))
        self.offsetTable.setColumnCount(2)
        self.offsetTable.setRowCount(3)
        item = QtGui.QTableWidgetItem()
        self.offsetTable.setVerticalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.offsetTable.setVerticalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.offsetTable.setVerticalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.offsetTable.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.offsetTable.setHorizontalHeaderItem(1, item)
        self.verticalLayout.addWidget(self.offsetTable)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.gridLayout_3 = QtGui.QGridLayout()
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.xpxPlot = matplotlibWidget(bunchInterface)
        self.xpxPlot.setToolTip(_fromUtf8(""))
        self.xpxPlot.setObjectName(_fromUtf8("xpxPlot"))
        self.gridLayout_3.addWidget(self.xpxPlot, 0, 0, 1, 1)
        self.ypyPlot = matplotlibWidget(bunchInterface)
        self.ypyPlot.setToolTip(_fromUtf8(""))
        self.ypyPlot.setObjectName(_fromUtf8("ypyPlot"))
        self.gridLayout_3.addWidget(self.ypyPlot, 0, 1, 1, 1)
        self.xyPlot = matplotlibWidget(bunchInterface)
        self.xyPlot.setToolTip(_fromUtf8(""))
        self.xyPlot.setObjectName(_fromUtf8("xyPlot"))
        self.gridLayout_3.addWidget(self.xyPlot, 1, 0, 1, 1)
        self.tpzPlot = matplotlibWidget(bunchInterface)
        self.tpzPlot.setToolTip(_fromUtf8(""))
        self.tpzPlot.setObjectName(_fromUtf8("tpzPlot"))
        self.gridLayout_3.addWidget(self.tpzPlot, 1, 1, 1, 1)
        self.horizontalLayout.addLayout(self.gridLayout_3)

        self.retranslateUi(bunchInterface)
        QtCore.QMetaObject.connectSlotsByName(bunchInterface)
        bunchInterface.setTabOrder(self.numPtcls, self.designMomentum)
        bunchInterface.setTabOrder(self.designMomentum, self.distribType)
        bunchInterface.setTabOrder(self.distribType, self.generateBunch)
        bunchInterface.setTabOrder(self.generateBunch, self.unitsPos)
        bunchInterface.setTabOrder(self.unitsPos, self.unitsAngle)
        bunchInterface.setTabOrder(self.unitsAngle, self.twissTable)
        bunchInterface.setTabOrder(self.twissTable, self.twissTableZ)
        bunchInterface.setTabOrder(self.twissTableZ, self.offsetTable)
        
        self.particleType = QtGui.QToolButton(bunchInterface)
        self.particleType.setText('Particle')
        self.particleType.setSizePolicy(QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed))
        self.gridLayout_2.addWidget(self.particleType,1,0,1,1)

    def retranslateUi(self, bunchInterface):
        bunchInterface.setWindowTitle(_translate("bunchInterface", "Form", None))
        self.distribType.setToolTip(_translate("bunchInterface", "Particle distribution type", None))
        self.distribType.setText(_translate("bunchInterface", "Distribution", None))
        self.noTitles.setText(_translate("bunchInterface", "Toggle Plot Titles", None))
        self.plotType.setText(_translate("bunchInterface", "Plot Type", None))
        self.generateBunch.setText(_translate("bunchInterface", "Generate Bunch", None))
        self.axisType.setText(_translate("bunchInterface", "Axis Limits", None))
        self.aspectRatio.setToolTip(_translate("bunchInterface", "Toggle aspect ratio of the x-y plot", None))
        self.aspectRatio.setText(_translate("bunchInterface", "Plot Aspect Ratio", None))
        self.highLevelInputsLabel.setText(_translate("bunchInterface", "Charge & Energy", None))
        self.unitsLabel.setText(_translate("bunchInterface", "Plotting units", None))
        self.numPtclsLabel.setText(_translate("bunchInterface", "Number of particles   ", None))
        self.unitsPosLabel.setText(_translate("bunchInterface", "Position     ", None))
        self.unitsPos.setToolTip(_translate("bunchInterface", "Units for position-like axes", None))
        self.designMomentumLabel.setText(_translate("bunchInterface", "Momentum [eV]", None))
        self.designMomentum.setToolTip(_translate("bunchInterface", "Average momentum for zero offset", None))
        self.unitsAngleLabel.setText(_translate("bunchInterface", "Angle", None))
        self.unitsAngle.setToolTip(_translate("bunchInterface", "Units for angle-like axes", None))
        self.charge.setText(_translate("bunchInterface", "Total charge [C]", None))
        self.ticksLabel.setText(_translate("bunchInterface", "Axis Ticks", None))
        self.numTicks.setToolTip(_translate("bunchInterface", "Maximum number of tick marks for plot axes", None))
        self.perpTwissLabel.setText(_translate("bunchInterface", "Twiss Parameters (rms, normalized)", None))
        self.perpTwissSpec.setToolTip(_translate("bunchInterface", "Transverse Twiss parameter specification", None))
        self.perpTwissSpec.setText(_translate("bunchInterface", "Spec", None))
        item = self.twissTable.verticalHeaderItem(0)
        item.setText(_translate("bunchInterface", "x-x\'", None))
        item = self.twissTable.verticalHeaderItem(1)
        item.setText(_translate("bunchInterface", "y-y\'", None))
        item = self.twissTable.horizontalHeaderItem(0)
        item.setText(_translate("bunchInterface", "alpha", None))
        item = self.twissTable.horizontalHeaderItem(1)
        item.setText(_translate("bunchInterface", "beta [m/rad]", None))
        item = self.twissTable.horizontalHeaderItem(2)
        item.setText(_translate("bunchInterface", "eps [m-rad]", None))
        __sortingEnabled = self.twissTable.isSortingEnabled()
        self.twissTable.setSortingEnabled(False)
        self.twissTable.setSortingEnabled(__sortingEnabled)
        self.longTwissLabel.setText(_translate("bunchInterface", "Longitudinal phase space (rms)", None))
        self.longTwissSpec.setToolTip(_translate("bunchInterface", "Longitudinal Twiss parameter specification", None))
        self.longTwissSpec.setText(_translate("bunchInterface", "Spec", None))
        item = self.twissTableZ.verticalHeaderItem(0)
        item.setText(_translate("bunchInterface", "s-dp", None))
        item = self.twissTableZ.horizontalHeaderItem(0)
        item.setText(_translate("bunchInterface", "alpha", None))
        item = self.twissTableZ.horizontalHeaderItem(1)
        item.setText(_translate("bunchInterface", "bct [m]", None))
        item = self.twissTableZ.horizontalHeaderItem(2)
        item.setText(_translate("bunchInterface", "dp/p [rad]", None))
        self.offsetLabel.setText(_translate("bunchInterface", "Beam offsets", None))
        item = self.offsetTable.verticalHeaderItem(0)
        item.setText(_translate("bunchInterface", "x-x\'", None))
        item = self.offsetTable.verticalHeaderItem(1)
        item.setText(_translate("bunchInterface", "y-y\'", None))
        item = self.offsetTable.verticalHeaderItem(2)
        item.setText(_translate("bunchInterface", "s-dp", None))
        item = self.offsetTable.horizontalHeaderItem(0)
        item.setText(_translate("bunchInterface", "position [m]", None))
        item = self.offsetTable.horizontalHeaderItem(1)
        item.setText(_translate("bunchInterface", "angle [rad]", None))

from radtrack.ui.matplotlibwidget import matplotlibWidget
