# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'iogenesis.ui'
#
# Created: Mon Mar 16 15:57:43 2015
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.resize(818, 478)
        self.buttonBox = QtGui.QDialogButtonBox(Dialog)
        self.buttonBox.setGeometry(QtCore.QRect(260, 440, 221, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.iphsty = QtGui.QCheckBox(Dialog)
        self.iphsty.setGeometry(QtCore.QRect(20, 10, 201, 18))
        self.iphsty.setObjectName(_fromUtf8("iphsty"))
        self.ishsty = QtGui.QCheckBox(Dialog)
        self.ishsty.setGeometry(QtCore.QRect(20, 40, 171, 18))
        self.ishsty.setObjectName(_fromUtf8("ishsty"))
        self.ippart = QtGui.QCheckBox(Dialog)
        self.ippart.setGeometry(QtCore.QRect(20, 60, 201, 41))
        self.ippart.setObjectName(_fromUtf8("ippart"))
        self.ispart = QtGui.QCheckBox(Dialog)
        self.ispart.setGeometry(QtCore.QRect(20, 110, 201, 31))
        self.ispart.setObjectName(_fromUtf8("ispart"))
        self.ipradi = QtGui.QCheckBox(Dialog)
        self.ipradi.setGeometry(QtCore.QRect(20, 150, 191, 31))
        self.ipradi.setObjectName(_fromUtf8("ipradi"))
        self.isradi = QtGui.QCheckBox(Dialog)
        self.isradi.setGeometry(QtCore.QRect(20, 190, 191, 41))
        self.isradi.setObjectName(_fromUtf8("isradi"))
        self.iotail = QtGui.QCheckBox(Dialog)
        self.iotail.setGeometry(QtCore.QRect(20, 300, 85, 18))
        self.iotail.setObjectName(_fromUtf8("iotail"))
        self.label_2 = QtGui.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(280, 40, 117, 21))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.magin = QtGui.QPushButton(Dialog)
        self.magin.setGeometry(QtCore.QRect(420, 35, 71, 32))
        self.magin.setObjectName(_fromUtf8("magin"))
        self.lineEdit_2 = QtGui.QLineEdit(Dialog)
        self.lineEdit_2.setGeometry(QtCore.QRect(490, 40, 111, 21))
        self.lineEdit_2.setObjectName(_fromUtf8("lineEdit_2"))
        self.label = QtGui.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(280, 10, 94, 21))
        self.label.setObjectName(_fromUtf8("label"))
        self.outputfile = QtGui.QPushButton(Dialog)
        self.outputfile.setGeometry(QtCore.QRect(420, 5, 71, 32))
        self.outputfile.setObjectName(_fromUtf8("outputfile"))
        self.lineEdit = QtGui.QLineEdit(Dialog)
        self.lineEdit.setGeometry(QtCore.QRect(490, 10, 111, 21))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit.sizePolicy().hasHeightForWidth())
        self.lineEdit.setSizePolicy(sizePolicy)
        self.lineEdit.setObjectName(_fromUtf8("lineEdit"))
        self.label_3 = QtGui.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(280, 70, 131, 16))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.lineEdit_3 = QtGui.QLineEdit(Dialog)
        self.lineEdit_3.setGeometry(QtCore.QRect(490, 65, 111, 21))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_3.sizePolicy().hasHeightForWidth())
        self.lineEdit_3.setSizePolicy(sizePolicy)
        self.lineEdit_3.setObjectName(_fromUtf8("lineEdit_3"))
        self.magout = QtGui.QPushButton(Dialog)
        self.magout.setGeometry(QtCore.QRect(420, 60, 71, 32))
        self.magout.setObjectName(_fromUtf8("magout"))
        self.dump = QtGui.QComboBox(Dialog)
        self.dump.setGeometry(QtCore.QRect(350, 330, 166, 26))
        self.dump.setObjectName(_fromUtf8("dump"))
        self.dump.addItem(_fromUtf8(""))
        self.dump.addItem(_fromUtf8(""))
        self.dump.addItem(_fromUtf8(""))
        self.label_4 = QtGui.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(290, 333, 61, 20))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.label_5 = QtGui.QLabel(Dialog)
        self.label_5.setGeometry(QtCore.QRect(280, 90, 117, 21))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.beamfile = QtGui.QPushButton(Dialog)
        self.beamfile.setGeometry(QtCore.QRect(420, 85, 71, 32))
        self.beamfile.setObjectName(_fromUtf8("beamfile"))
        self.lineEdit_4 = QtGui.QLineEdit(Dialog)
        self.lineEdit_4.setGeometry(QtCore.QRect(490, 90, 111, 21))
        self.lineEdit_4.setText(_fromUtf8(""))
        self.lineEdit_4.setObjectName(_fromUtf8("lineEdit_4"))
        self.label_6 = QtGui.QLabel(Dialog)
        self.label_6.setGeometry(QtCore.QRect(280, 125, 131, 16))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.lineEdit_5 = QtGui.QLineEdit(Dialog)
        self.lineEdit_5.setGeometry(QtCore.QRect(490, 120, 111, 21))
        self.lineEdit_5.setText(_fromUtf8(""))
        self.lineEdit_5.setObjectName(_fromUtf8("lineEdit_5"))
        self.radfile = QtGui.QPushButton(Dialog)
        self.radfile.setGeometry(QtCore.QRect(420, 115, 71, 32))
        self.radfile.setObjectName(_fromUtf8("radfile"))
        self.label_7 = QtGui.QLabel(Dialog)
        self.label_7.setGeometry(QtCore.QRect(280, 155, 141, 16))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.lineEdit_6 = QtGui.QLineEdit(Dialog)
        self.lineEdit_6.setGeometry(QtCore.QRect(490, 150, 111, 21))
        self.lineEdit_6.setText(_fromUtf8(""))
        self.lineEdit_6.setObjectName(_fromUtf8("lineEdit_6"))
        self.distfile = QtGui.QPushButton(Dialog)
        self.distfile.setGeometry(QtCore.QRect(420, 145, 71, 32))
        self.distfile.setObjectName(_fromUtf8("distfile"))
        self.ndcut = QtGui.QCheckBox(Dialog)
        self.ndcut.setGeometry(QtCore.QRect(20, 280, 85, 18))
        self.ndcut.setObjectName(_fromUtf8("ndcut"))
        self.label_8 = QtGui.QLabel(Dialog)
        self.label_8.setGeometry(QtCore.QRect(280, 185, 151, 16))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.lineEdit_7 = QtGui.QLineEdit(Dialog)
        self.lineEdit_7.setGeometry(QtCore.QRect(490, 180, 111, 21))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_7.sizePolicy().hasHeightForWidth())
        self.lineEdit_7.setSizePolicy(sizePolicy)
        self.lineEdit_7.setObjectName(_fromUtf8("lineEdit_7"))
        self.fieldfile = QtGui.QPushButton(Dialog)
        self.fieldfile.setGeometry(QtCore.QRect(420, 177, 71, 32))
        self.fieldfile.setObjectName(_fromUtf8("fieldfile"))
        self.alignradf = QtGui.QCheckBox(Dialog)
        self.alignradf.setGeometry(QtCore.QRect(20, 240, 161, 18))
        self.alignradf.setObjectName(_fromUtf8("alignradf"))
        self.label_9 = QtGui.QLabel(Dialog)
        self.label_9.setGeometry(QtCore.QRect(630, 15, 101, 16))
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.offsetradf = QtGui.QLineEdit(Dialog)
        self.offsetradf.setGeometry(QtCore.QRect(730, 12, 71, 21))
        self.offsetradf.setObjectName(_fromUtf8("offsetradf"))
        self.lineEdit_9 = QtGui.QLineEdit(Dialog)
        self.lineEdit_9.setGeometry(QtCore.QRect(490, 215, 111, 21))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_9.sizePolicy().hasHeightForWidth())
        self.lineEdit_9.setSizePolicy(sizePolicy)
        self.lineEdit_9.setObjectName(_fromUtf8("lineEdit_9"))
        self.label_10 = QtGui.QLabel(Dialog)
        self.label_10.setGeometry(QtCore.QRect(280, 213, 151, 31))
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.partfile = QtGui.QPushButton(Dialog)
        self.partfile.setGeometry(QtCore.QRect(420, 210, 71, 32))
        self.partfile.setObjectName(_fromUtf8("partfile"))
        self.label_11 = QtGui.QLabel(Dialog)
        self.label_11.setGeometry(QtCore.QRect(630, 45, 81, 16))
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.convharm = QtGui.QLineEdit(Dialog)
        self.convharm.setGeometry(QtCore.QRect(730, 40, 71, 21))
        self.convharm.setObjectName(_fromUtf8("convharm"))
        self.label_12 = QtGui.QLabel(Dialog)
        self.label_12.setGeometry(QtCore.QRect(630, 75, 81, 16))
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.multiconv = QtGui.QLineEdit(Dialog)
        self.multiconv.setGeometry(QtCore.QRect(730, 70, 71, 21))
        self.multiconv.setObjectName(_fromUtf8("multiconv"))
        self.label_13 = QtGui.QLabel(Dialog)
        self.label_13.setGeometry(QtCore.QRect(630, 110, 56, 13))
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.imagl = QtGui.QLineEdit(Dialog)
        self.imagl.setGeometry(QtCore.QRect(730, 100, 71, 21))
        self.imagl.setObjectName(_fromUtf8("imagl"))
        self.label_14 = QtGui.QLabel(Dialog)
        self.label_14.setGeometry(QtCore.QRect(630, 140, 56, 13))
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.idril = QtGui.QLineEdit(Dialog)
        self.idril.setGeometry(QtCore.QRect(730, 130, 71, 21))
        self.idril.setObjectName(_fromUtf8("idril"))
        self.label_15 = QtGui.QLabel(Dialog)
        self.label_15.setGeometry(QtCore.QRect(290, 373, 101, 16))
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.trama = QtGui.QPushButton(Dialog)
        self.trama.setGeometry(QtCore.QRect(390, 365, 110, 32))
        self.trama.setObjectName(_fromUtf8("trama"))
        self.ilog = QtGui.QCheckBox(Dialog)
        self.ilog.setGeometry(QtCore.QRect(20, 260, 85, 18))
        self.ilog.setObjectName(_fromUtf8("ilog"))
        self.label_16 = QtGui.QLabel(Dialog)
        self.label_16.setGeometry(QtCore.QRect(630, 170, 56, 13))
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.ibfield = QtGui.QLineEdit(Dialog)
        self.ibfield.setGeometry(QtCore.QRect(730, 160, 71, 21))
        self.ibfield.setObjectName(_fromUtf8("ibfield"))
        self.ffspec = QtGui.QComboBox(Dialog)
        self.ffspec.setGeometry(QtCore.QRect(350, 295, 161, 26))
        self.ffspec.setObjectName(_fromUtf8("ffspec"))
        self.ffspec.addItem(_fromUtf8(""))
        self.ffspec.addItem(_fromUtf8(""))
        self.ffspec.addItem(_fromUtf8(""))
        self.label_17 = QtGui.QLabel(Dialog)
        self.label_17.setGeometry(QtCore.QRect(290, 305, 56, 13))
        self.label_17.setObjectName(_fromUtf8("label_17"))

        self.retranslateUi(Dialog)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), Dialog.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(_translate("Dialog", "Dialog", None))
        self.iphsty.setText(_translate("Dialog", "Output at each integration step", None))
        self.ishsty.setText(_translate("Dialog", "Output at each slice", None))
        self.ippart.setText(_translate("Dialog", "Output Particle Distribution at \n"
"each integration step", None))
        self.ispart.setText(_translate("Dialog", "Output Particle Distribution at \n"
"each slice", None))
        self.ipradi.setText(_translate("Dialog", "Output Field Distribution at \n"
"each integration step", None))
        self.isradi.setText(_translate("Dialog", "Output Field Distribution at\n"
"each slice", None))
        self.iotail.setText(_translate("Dialog", "IOTAIL", None))
        self.label_2.setText(_translate("Dialog", "Magnetic Field Input", None))
        self.magin.setText(_translate("Dialog", "Import", None))
        self.label.setText(_translate("Dialog", "Output file", None))
        self.outputfile.setText(_translate("Dialog", "Export", None))
        self.label_3.setText(_translate("Dialog", "Magnetic Field Output", None))
        self.magout.setText(_translate("Dialog", "Export", None))
        self.dump.setItemText(0, _translate("Dialog", "Field", None))
        self.dump.setItemText(1, _translate("Dialog", "Distribution", None))
        self.dump.setItemText(2, _translate("Dialog", "Field & Distribuition", None))
        self.label_4.setText(_translate("Dialog", "Dump the", None))
        self.label_5.setText(_translate("Dialog", "Beam Input", None))
        self.beamfile.setText(_translate("Dialog", "Import", None))
        self.label_6.setText(_translate("Dialog", "Seed Radiation Input", None))
        self.radfile.setText(_translate("Dialog", "Import", None))
        self.label_7.setText(_translate("Dialog", "6D Phase Space Input", None))
        self.distfile.setText(_translate("Dialog", "Import", None))
        self.ndcut.setText(_translate("Dialog", "NDCUT", None))
        self.label_8.setText(_translate("Dialog", "Field Distribution Output", None))
        self.fieldfile.setText(_translate("Dialog", "Import", None))
        self.alignradf.setText(_translate("Dialog", "Align Radiation Field", None))
        self.label_9.setText(_translate("Dialog", "Offset Radiation", None))
        self.label_10.setText(_translate("Dialog", "Particle Distribution\n"
"Output", None))
        self.partfile.setText(_translate("Dialog", "Import", None))
        self.label_11.setText(_translate("Dialog", "CONVHARM", None))
        self.label_12.setText(_translate("Dialog", "MULTICONV", None))
        self.label_13.setText(_translate("Dialog", "IMAGL", None))
        self.label_14.setText(_translate("Dialog", "IDRIL", None))
        self.label_15.setText(_translate("Dialog", "Transport Matrix", None))
        self.trama.setText(_translate("Dialog", "define matrix", None))
        self.ilog.setText(_translate("Dialog", "Log", None))
        self.label_16.setText(_translate("Dialog", "IBFIELD", None))
        self.ffspec.setItemText(0, _translate("Dialog", "near field", None))
        self.ffspec.setItemText(1, _translate("Dialog", "far field", None))
        self.ffspec.setItemText(2, _translate("Dialog", "total radiation power", None))
        self.label_17.setText(_translate("Dialog", "FFSPEC", None))

