# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'iogenesis.ui'
#
# Created: Sun Mar 15 02:09:18 2015
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.resize(818, 478)
        self.buttonBox = QtGui.QDialogButtonBox(Dialog)
        self.buttonBox.setGeometry(QtCore.QRect(260, 440, 221, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.checkBox = QtGui.QCheckBox(Dialog)
        self.checkBox.setGeometry(QtCore.QRect(20, 10, 201, 18))
        self.checkBox.setObjectName(_fromUtf8("checkBox"))
        self.checkBox_2 = QtGui.QCheckBox(Dialog)
        self.checkBox_2.setGeometry(QtCore.QRect(20, 40, 171, 18))
        self.checkBox_2.setObjectName(_fromUtf8("checkBox_2"))
        self.checkBox_3 = QtGui.QCheckBox(Dialog)
        self.checkBox_3.setGeometry(QtCore.QRect(20, 60, 201, 41))
        self.checkBox_3.setObjectName(_fromUtf8("checkBox_3"))
        self.checkBox_4 = QtGui.QCheckBox(Dialog)
        self.checkBox_4.setGeometry(QtCore.QRect(20, 110, 201, 31))
        self.checkBox_4.setObjectName(_fromUtf8("checkBox_4"))
        self.checkBox_5 = QtGui.QCheckBox(Dialog)
        self.checkBox_5.setGeometry(QtCore.QRect(20, 150, 191, 31))
        self.checkBox_5.setObjectName(_fromUtf8("checkBox_5"))
        self.checkBox_6 = QtGui.QCheckBox(Dialog)
        self.checkBox_6.setGeometry(QtCore.QRect(20, 190, 191, 41))
        self.checkBox_6.setObjectName(_fromUtf8("checkBox_6"))
        self.checkBox_7 = QtGui.QCheckBox(Dialog)
        self.checkBox_7.setGeometry(QtCore.QRect(20, 330, 85, 18))
        self.checkBox_7.setObjectName(_fromUtf8("checkBox_7"))
        self.label_2 = QtGui.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(280, 40, 117, 21))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.pushButton_2 = QtGui.QPushButton(Dialog)
        self.pushButton_2.setGeometry(QtCore.QRect(420, 35, 71, 32))
        self.pushButton_2.setObjectName(_fromUtf8("pushButton_2"))
        self.lineEdit_2 = QtGui.QLineEdit(Dialog)
        self.lineEdit_2.setGeometry(QtCore.QRect(490, 40, 111, 21))
        self.lineEdit_2.setObjectName(_fromUtf8("lineEdit_2"))
        self.label = QtGui.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(280, 10, 94, 21))
        self.label.setObjectName(_fromUtf8("label"))
        self.pushButton = QtGui.QPushButton(Dialog)
        self.pushButton.setGeometry(QtCore.QRect(420, 5, 71, 32))
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.lineEdit = QtGui.QLineEdit(Dialog)
        self.lineEdit.setGeometry(QtCore.QRect(490, 10, 111, 21))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit.sizePolicy().hasHeightForWidth())
        self.lineEdit.setSizePolicy(sizePolicy)
        self.lineEdit.setObjectName(_fromUtf8("lineEdit"))
        self.label_3 = QtGui.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(280, 70, 131, 16))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.lineEdit_3 = QtGui.QLineEdit(Dialog)
        self.lineEdit_3.setGeometry(QtCore.QRect(490, 65, 111, 21))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_3.sizePolicy().hasHeightForWidth())
        self.lineEdit_3.setSizePolicy(sizePolicy)
        self.lineEdit_3.setObjectName(_fromUtf8("lineEdit_3"))
        self.pushButton_3 = QtGui.QPushButton(Dialog)
        self.pushButton_3.setGeometry(QtCore.QRect(420, 60, 71, 32))
        self.pushButton_3.setObjectName(_fromUtf8("pushButton_3"))
        self.dump = QtGui.QComboBox(Dialog)
        self.dump.setGeometry(QtCore.QRect(380, 295, 166, 26))
        self.dump.setObjectName(_fromUtf8("dump"))
        self.dump.addItem(_fromUtf8(""))
        self.dump.addItem(_fromUtf8(""))
        self.dump.addItem(_fromUtf8(""))
        self.label_4 = QtGui.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(320, 298, 61, 20))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.label_5 = QtGui.QLabel(Dialog)
        self.label_5.setGeometry(QtCore.QRect(280, 90, 117, 21))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.pushButton_4 = QtGui.QPushButton(Dialog)
        self.pushButton_4.setGeometry(QtCore.QRect(420, 85, 71, 32))
        self.pushButton_4.setObjectName(_fromUtf8("pushButton_4"))
        self.lineEdit_4 = QtGui.QLineEdit(Dialog)
        self.lineEdit_4.setGeometry(QtCore.QRect(490, 90, 111, 21))
        self.lineEdit_4.setText(_fromUtf8(""))
        self.lineEdit_4.setObjectName(_fromUtf8("lineEdit_4"))
        self.label_6 = QtGui.QLabel(Dialog)
        self.label_6.setGeometry(QtCore.QRect(280, 125, 131, 16))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.lineEdit_5 = QtGui.QLineEdit(Dialog)
        self.lineEdit_5.setGeometry(QtCore.QRect(490, 120, 111, 21))
        self.lineEdit_5.setText(_fromUtf8(""))
        self.lineEdit_5.setObjectName(_fromUtf8("lineEdit_5"))
        self.pushButton_5 = QtGui.QPushButton(Dialog)
        self.pushButton_5.setGeometry(QtCore.QRect(420, 115, 71, 32))
        self.pushButton_5.setObjectName(_fromUtf8("pushButton_5"))
        self.label_7 = QtGui.QLabel(Dialog)
        self.label_7.setGeometry(QtCore.QRect(280, 155, 141, 16))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.lineEdit_6 = QtGui.QLineEdit(Dialog)
        self.lineEdit_6.setGeometry(QtCore.QRect(490, 150, 111, 21))
        self.lineEdit_6.setText(_fromUtf8(""))
        self.lineEdit_6.setObjectName(_fromUtf8("lineEdit_6"))
        self.pushButton_6 = QtGui.QPushButton(Dialog)
        self.pushButton_6.setGeometry(QtCore.QRect(420, 145, 71, 32))
        self.pushButton_6.setObjectName(_fromUtf8("pushButton_6"))
        self.checkBox_8 = QtGui.QCheckBox(Dialog)
        self.checkBox_8.setGeometry(QtCore.QRect(20, 310, 85, 18))
        self.checkBox_8.setObjectName(_fromUtf8("checkBox_8"))
        self.label_8 = QtGui.QLabel(Dialog)
        self.label_8.setGeometry(QtCore.QRect(280, 185, 151, 16))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.lineEdit_7 = QtGui.QLineEdit(Dialog)
        self.lineEdit_7.setGeometry(QtCore.QRect(490, 180, 111, 21))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_7.sizePolicy().hasHeightForWidth())
        self.lineEdit_7.setSizePolicy(sizePolicy)
        self.lineEdit_7.setObjectName(_fromUtf8("lineEdit_7"))
        self.pushButton_7 = QtGui.QPushButton(Dialog)
        self.pushButton_7.setGeometry(QtCore.QRect(420, 177, 71, 32))
        self.pushButton_7.setObjectName(_fromUtf8("pushButton_7"))
        self.checkBox_9 = QtGui.QCheckBox(Dialog)
        self.checkBox_9.setGeometry(QtCore.QRect(20, 240, 161, 18))
        self.checkBox_9.setObjectName(_fromUtf8("checkBox_9"))
        self.label_9 = QtGui.QLabel(Dialog)
        self.label_9.setGeometry(QtCore.QRect(630, 15, 101, 16))
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.lineEdit_8 = QtGui.QLineEdit(Dialog)
        self.lineEdit_8.setGeometry(QtCore.QRect(730, 12, 71, 21))
        self.lineEdit_8.setObjectName(_fromUtf8("lineEdit_8"))
        self.lineEdit_9 = QtGui.QLineEdit(Dialog)
        self.lineEdit_9.setGeometry(QtCore.QRect(490, 215, 111, 21))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_9.sizePolicy().hasHeightForWidth())
        self.lineEdit_9.setSizePolicy(sizePolicy)
        self.lineEdit_9.setObjectName(_fromUtf8("lineEdit_9"))
        self.label_10 = QtGui.QLabel(Dialog)
        self.label_10.setGeometry(QtCore.QRect(280, 213, 151, 31))
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.pushButton_8 = QtGui.QPushButton(Dialog)
        self.pushButton_8.setGeometry(QtCore.QRect(420, 210, 71, 32))
        self.pushButton_8.setObjectName(_fromUtf8("pushButton_8"))
        self.label_11 = QtGui.QLabel(Dialog)
        self.label_11.setGeometry(QtCore.QRect(630, 45, 81, 16))
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.lineEdit_10 = QtGui.QLineEdit(Dialog)
        self.lineEdit_10.setGeometry(QtCore.QRect(730, 40, 71, 21))
        self.lineEdit_10.setObjectName(_fromUtf8("lineEdit_10"))
        self.label_12 = QtGui.QLabel(Dialog)
        self.label_12.setGeometry(QtCore.QRect(630, 75, 81, 16))
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.lineEdit_11 = QtGui.QLineEdit(Dialog)
        self.lineEdit_11.setGeometry(QtCore.QRect(730, 70, 71, 21))
        self.lineEdit_11.setObjectName(_fromUtf8("lineEdit_11"))
        self.label_13 = QtGui.QLabel(Dialog)
        self.label_13.setGeometry(QtCore.QRect(630, 110, 56, 13))
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.lineEdit_12 = QtGui.QLineEdit(Dialog)
        self.lineEdit_12.setGeometry(QtCore.QRect(730, 100, 71, 21))
        self.lineEdit_12.setObjectName(_fromUtf8("lineEdit_12"))
        self.label_14 = QtGui.QLabel(Dialog)
        self.label_14.setGeometry(QtCore.QRect(630, 140, 56, 13))
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.lineEdit_13 = QtGui.QLineEdit(Dialog)
        self.lineEdit_13.setGeometry(QtCore.QRect(730, 130, 71, 21))
        self.lineEdit_13.setObjectName(_fromUtf8("lineEdit_13"))
        self.label_15 = QtGui.QLabel(Dialog)
        self.label_15.setGeometry(QtCore.QRect(320, 338, 101, 16))
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.pushButton_9 = QtGui.QPushButton(Dialog)
        self.pushButton_9.setGeometry(QtCore.QRect(420, 330, 110, 32))
        self.pushButton_9.setObjectName(_fromUtf8("pushButton_9"))
        self.checkBox_10 = QtGui.QCheckBox(Dialog)
        self.checkBox_10.setGeometry(QtCore.QRect(20, 260, 85, 18))
        self.checkBox_10.setObjectName(_fromUtf8("checkBox_10"))
        self.checkBox_11 = QtGui.QCheckBox(Dialog)
        self.checkBox_11.setGeometry(QtCore.QRect(20, 290, 85, 18))
        self.checkBox_11.setObjectName(_fromUtf8("checkBox_11"))

        self.retranslateUi(Dialog)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), Dialog.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(_translate("Dialog", "Dialog", None))
        self.checkBox.setText(_translate("Dialog", "Output at each integration step", None))
        self.checkBox_2.setText(_translate("Dialog", "Output at each slice", None))
        self.checkBox_3.setText(_translate("Dialog", "Output Particle Distribution at \n"
"each integration step", None))
        self.checkBox_4.setText(_translate("Dialog", "Output Particle Distribution at \n"
"each slice", None))
        self.checkBox_5.setText(_translate("Dialog", "Output Field Distribution at \n"
"each integration step", None))
        self.checkBox_6.setText(_translate("Dialog", "Output Field Distribution at\n"
"each slice", None))
        self.checkBox_7.setText(_translate("Dialog", "IOTAIL", None))
        self.label_2.setText(_translate("Dialog", "Magnetic Field Input", None))
        self.pushButton_2.setText(_translate("Dialog", "Import", None))
        self.label.setText(_translate("Dialog", "Output file", None))
        self.pushButton.setText(_translate("Dialog", "Export", None))
        self.label_3.setText(_translate("Dialog", "Magnetic Field Output", None))
        self.pushButton_3.setText(_translate("Dialog", "Export", None))
        self.dump.setItemText(0, _translate("Dialog", "Field", None))
        self.dump.setItemText(1, _translate("Dialog", "Distribution", None))
        self.dump.setItemText(2, _translate("Dialog", "Field & Distribuition", None))
        self.label_4.setText(_translate("Dialog", "Dump the", None))
        self.label_5.setText(_translate("Dialog", "Beam Input", None))
        self.pushButton_4.setText(_translate("Dialog", "Import", None))
        self.label_6.setText(_translate("Dialog", "Seed Radiation Input", None))
        self.pushButton_5.setText(_translate("Dialog", "Import", None))
        self.label_7.setText(_translate("Dialog", "6D Phase Space Input", None))
        self.pushButton_6.setText(_translate("Dialog", "Import", None))
        self.checkBox_8.setText(_translate("Dialog", "NDCUT", None))
        self.label_8.setText(_translate("Dialog", "Field Distribution Output", None))
        self.pushButton_7.setText(_translate("Dialog", "Import", None))
        self.checkBox_9.setText(_translate("Dialog", "Align Radiation Field", None))
        self.label_9.setText(_translate("Dialog", "Offset Radiation", None))
        self.label_10.setText(_translate("Dialog", "Particle Distribution\n"
"Output", None))
        self.pushButton_8.setText(_translate("Dialog", "Import", None))
        self.label_11.setText(_translate("Dialog", "CONVHARM", None))
        self.label_12.setText(_translate("Dialog", "MULTICONV", None))
        self.label_13.setText(_translate("Dialog", "IMAGL", None))
        self.label_14.setText(_translate("Dialog", "IDRIL", None))
        self.label_15.setText(_translate("Dialog", "Transport Matrix", None))
        self.pushButton_9.setText(_translate("Dialog", "define matrix", None))
        self.checkBox_10.setText(_translate("Dialog", "Log", None))
        self.checkBox_11.setText(_translate("Dialog", "FFSPEC", None))

