# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'newsrw.ui'
#
# Created: Mon Feb 23 01:46:35 2015
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName(_fromUtf8("Form"))
        Form.resize(745, 557)
        self.gridLayoutWidget = QtGui.QWidget(Form)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(40, 20, 659, 121))
        self.gridLayoutWidget.setObjectName(_fromUtf8("gridLayoutWidget"))
        self.gridLayout = QtGui.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setMargin(0)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.pushButton = QtGui.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton.sizePolicy().hasHeightForWidth())
        self.pushButton.setSizePolicy(sizePolicy)
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.gridLayout.addWidget(self.pushButton, 0, 0, 1, 1)
        self.pushButton_3 = QtGui.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_3.sizePolicy().hasHeightForWidth())
        self.pushButton_3.setSizePolicy(sizePolicy)
        self.pushButton_3.setObjectName(_fromUtf8("pushButton_3"))
        self.gridLayout.addWidget(self.pushButton_3, 0, 2, 1, 1)
        self.pushButton_2 = QtGui.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_2.sizePolicy().hasHeightForWidth())
        self.pushButton_2.setSizePolicy(sizePolicy)
        self.pushButton_2.setObjectName(_fromUtf8("pushButton_2"))
        self.gridLayout.addWidget(self.pushButton_2, 0, 1, 1, 1)
        self.pushButton_4 = QtGui.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_4.sizePolicy().hasHeightForWidth())
        self.pushButton_4.setSizePolicy(sizePolicy)
        self.pushButton_4.setObjectName(_fromUtf8("pushButton_4"))
        self.gridLayout.addWidget(self.pushButton_4, 0, 3, 1, 1)
        self.formLayoutWidget_4 = QtGui.QWidget(Form)
        self.formLayoutWidget_4.setGeometry(QtCore.QRect(40, 160, 291, 82))
        self.formLayoutWidget_4.setObjectName(_fromUtf8("formLayoutWidget_4"))
        self.formLayout_4 = QtGui.QFormLayout(self.formLayoutWidget_4)
        self.formLayout_4.setLabelAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.formLayout_4.setFormAlignment(QtCore.Qt.AlignCenter)
        self.formLayout_4.setMargin(0)
        self.formLayout_4.setObjectName(_fromUtf8("formLayout_4"))
        self.label_31 = QtGui.QLabel(self.formLayoutWidget_4)
        self.label_31.setObjectName(_fromUtf8("label_31"))
        self.formLayout_4.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_31)
        self.label_32 = QtGui.QLabel(self.formLayoutWidget_4)
        self.label_32.setObjectName(_fromUtf8("label_32"))
        self.formLayout_4.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_32)
        self.comboBox_3 = QtGui.QComboBox(self.formLayoutWidget_4)
        self.comboBox_3.setObjectName(_fromUtf8("comboBox_3"))
        self.comboBox_3.addItem(_fromUtf8(""))
        self.comboBox_3.addItem(_fromUtf8(""))
        self.comboBox_3.addItem(_fromUtf8(""))
        self.comboBox_3.addItem(_fromUtf8(""))
        self.comboBox_3.addItem(_fromUtf8(""))
        self.comboBox_3.addItem(_fromUtf8(""))
        self.comboBox_3.addItem(_fromUtf8(""))
        self.formLayout_4.setWidget(1, QtGui.QFormLayout.FieldRole, self.comboBox_3)
        self.label_33 = QtGui.QLabel(self.formLayoutWidget_4)
        self.label_33.setObjectName(_fromUtf8("label_33"))
        self.formLayout_4.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_33)
        self.comboBox_4 = QtGui.QComboBox(self.formLayoutWidget_4)
        self.comboBox_4.setObjectName(_fromUtf8("comboBox_4"))
        self.comboBox_4.addItem(_fromUtf8(""))
        self.comboBox_4.addItem(_fromUtf8(""))
        self.comboBox_4.addItem(_fromUtf8(""))
        self.comboBox_4.addItem(_fromUtf8(""))
        self.comboBox_4.addItem(_fromUtf8(""))
        self.comboBox_4.addItem(_fromUtf8(""))
        self.comboBox_4.addItem(_fromUtf8(""))
        self.formLayout_4.setWidget(2, QtGui.QFormLayout.FieldRole, self.comboBox_4)
        self.comboBox_5 = QtGui.QComboBox(self.formLayoutWidget_4)
        self.comboBox_5.setObjectName(_fromUtf8("comboBox_5"))
        self.comboBox_5.addItem(_fromUtf8(""))
        self.comboBox_5.addItem(_fromUtf8(""))
        self.comboBox_5.addItem(_fromUtf8(""))
        self.comboBox_5.addItem(_fromUtf8(""))
        self.comboBox_5.addItem(_fromUtf8(""))
        self.comboBox_5.addItem(_fromUtf8(""))
        self.comboBox_5.addItem(_fromUtf8(""))
        self.formLayout_4.setWidget(0, QtGui.QFormLayout.FieldRole, self.comboBox_5)
        self.tableWidget = QtGui.QTableWidget(Form)
        self.tableWidget.setGeometry(QtCore.QRect(430, 160, 271, 321))
        self.tableWidget.setObjectName(_fromUtf8("tableWidget"))
        self.tableWidget.setColumnCount(1)
        self.tableWidget.setRowCount(10)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(6, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(7, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(8, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(9, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        self.graphicsView = QtGui.QGraphicsView(Form)
        self.graphicsView.setGeometry(QtCore.QRect(40, 270, 291, 192))
        self.graphicsView.setObjectName(_fromUtf8("graphicsView"))

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(_translate("Form", "Form", None))
        self.pushButton.setText(_translate("Form", "Undulator", None))
        self.pushButton_3.setText(_translate("Form", "Precision", None))
        self.pushButton_2.setText(_translate("Form", "Beam", None))
        self.pushButton_4.setText(_translate("Form", "Simulate", None))
        self.label_31.setText(_translate("Form", "Polarization", None))
        self.label_32.setText(_translate("Form", "Intensity", None))
        self.comboBox_3.setItemText(0, _translate("Form", "Single Electron Intensity", None))
        self.comboBox_3.setItemText(1, _translate("Form", "Multi Electron Intensity", None))
        self.comboBox_3.setItemText(2, _translate("Form", "Single Electron FLux", None))
        self.comboBox_3.setItemText(3, _translate("Form", "Multi Electron FLux", None))
        self.comboBox_3.setItemText(4, _translate("Form", "Single Electron Radiation Phase", None))
        self.comboBox_3.setItemText(5, _translate("Form", "Real Part of Electron E-Field", None))
        self.comboBox_3.setItemText(6, _translate("Form", "Imaginary Part of Electron E-Field", None))
        self.label_33.setText(_translate("Form", "Dependent Argument", None))
        self.comboBox_4.setItemText(0, _translate("Form", "e (energy)", None))
        self.comboBox_4.setItemText(1, _translate("Form", "x (horizontal)", None))
        self.comboBox_4.setItemText(2, _translate("Form", "y (vertical)", None))
        self.comboBox_4.setItemText(3, _translate("Form", "x & y", None))
        self.comboBox_4.setItemText(4, _translate("Form", "e & x", None))
        self.comboBox_4.setItemText(5, _translate("Form", "e & y", None))
        self.comboBox_4.setItemText(6, _translate("Form", "e & x & y", None))
        self.comboBox_5.setItemText(0, _translate("Form", "Linear Horizontal", None))
        self.comboBox_5.setItemText(1, _translate("Form", "Linear Vertical", None))
        self.comboBox_5.setItemText(2, _translate("Form", "Linear 45 Degrees", None))
        self.comboBox_5.setItemText(3, _translate("Form", "Linear 135 Degrees", None))
        self.comboBox_5.setItemText(4, _translate("Form", "Circular Right", None))
        self.comboBox_5.setItemText(5, _translate("Form", "Circular", None))
        self.comboBox_5.setItemText(6, _translate("Form", "Total", None))
        item = self.tableWidget.verticalHeaderItem(0)
        item.setText(_translate("Form", "Number of points along Enrgy", None))
        item = self.tableWidget.verticalHeaderItem(1)
        item.setText(_translate("Form", "Number of Points along X", None))
        item = self.tableWidget.verticalHeaderItem(2)
        item.setText(_translate("Form", "Number of points along Y", None))
        item = self.tableWidget.verticalHeaderItem(3)
        item.setText(_translate("Form", "Positin to calculate SR", None))
        item = self.tableWidget.verticalHeaderItem(4)
        item.setText(_translate("Form", "Inital Photon Energy", None))
        item = self.tableWidget.verticalHeaderItem(5)
        item.setText(_translate("Form", "Final Photon Energy", None))
        item = self.tableWidget.verticalHeaderItem(6)
        item.setText(_translate("Form", "Inital X position", None))
        item = self.tableWidget.verticalHeaderItem(7)
        item.setText(_translate("Form", "Inital Y position", None))
        item = self.tableWidget.verticalHeaderItem(8)
        item.setText(_translate("Form", "Final X position", None))
        item = self.tableWidget.verticalHeaderItem(9)
        item.setText(_translate("Form", "Final Y position", None))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Form", "Mesh", None))

