# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'newsrw.ui'
#
# Created: Thu Feb 26 11:32:51 2015
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName(_fromUtf8("Form"))
        Form.resize(812, 605)
        self.gridLayoutWidget = QtGui.QWidget(Form)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(40, 20, 739, 121))
        self.gridLayoutWidget.setObjectName(_fromUtf8("gridLayoutWidget"))
        self.gridLayout = QtGui.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setMargin(0)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.sim = QtGui.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sim.sizePolicy().hasHeightForWidth())
        self.sim.setSizePolicy(sizePolicy)
        self.sim.setObjectName(_fromUtf8("sim"))
        self.gridLayout.addWidget(self.sim, 0, 3, 1, 1)
        self.beam = QtGui.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.beam.sizePolicy().hasHeightForWidth())
        self.beam.setSizePolicy(sizePolicy)
        self.beam.setObjectName(_fromUtf8("beam"))
        self.gridLayout.addWidget(self.beam, 0, 1, 1, 1)
        self.undulator = QtGui.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.undulator.sizePolicy().hasHeightForWidth())
        self.undulator.setSizePolicy(sizePolicy)
        self.undulator.setObjectName(_fromUtf8("undulator"))
        self.gridLayout.addWidget(self.undulator, 0, 0, 1, 1)
        self.precision = QtGui.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.precision.sizePolicy().hasHeightForWidth())
        self.precision.setSizePolicy(sizePolicy)
        self.precision.setObjectName(_fromUtf8("precision"))
        self.gridLayout.addWidget(self.precision, 0, 2, 1, 1)
        self.plot = QtGui.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.plot.sizePolicy().hasHeightForWidth())
        self.plot.setSizePolicy(sizePolicy)
        self.plot.setObjectName(_fromUtf8("plot"))
        self.gridLayout.addWidget(self.plot, 0, 4, 1, 1)
        self.formLayoutWidget_4 = QtGui.QWidget(Form)
        self.formLayoutWidget_4.setGeometry(QtCore.QRect(40, 160, 291, 82))
        self.formLayoutWidget_4.setObjectName(_fromUtf8("formLayoutWidget_4"))
        self.formLayout_4 = QtGui.QFormLayout(self.formLayoutWidget_4)
        self.formLayout_4.setLabelAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.formLayout_4.setFormAlignment(QtCore.Qt.AlignCenter)
        self.formLayout_4.setMargin(0)
        self.formLayout_4.setObjectName(_fromUtf8("formLayout_4"))
        self.label_31 = QtGui.QLabel(self.formLayoutWidget_4)
        self.label_31.setObjectName(_fromUtf8("label_31"))
        self.formLayout_4.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_31)
        self.label_32 = QtGui.QLabel(self.formLayoutWidget_4)
        self.label_32.setObjectName(_fromUtf8("label_32"))
        self.formLayout_4.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_32)
        self.intesity = QtGui.QComboBox(self.formLayoutWidget_4)
        self.intesity.setObjectName(_fromUtf8("intesity"))
        self.intesity.addItem(_fromUtf8(""))
        self.intesity.addItem(_fromUtf8(""))
        self.intesity.addItem(_fromUtf8(""))
        self.intesity.addItem(_fromUtf8(""))
        self.intesity.addItem(_fromUtf8(""))
        self.intesity.addItem(_fromUtf8(""))
        self.intesity.addItem(_fromUtf8(""))
        self.formLayout_4.setWidget(1, QtGui.QFormLayout.FieldRole, self.intesity)
        self.label_33 = QtGui.QLabel(self.formLayoutWidget_4)
        self.label_33.setObjectName(_fromUtf8("label_33"))
        self.formLayout_4.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_33)
        self.deparg = QtGui.QComboBox(self.formLayoutWidget_4)
        self.deparg.setObjectName(_fromUtf8("deparg"))
        self.deparg.addItem(_fromUtf8(""))
        self.deparg.addItem(_fromUtf8(""))
        self.deparg.addItem(_fromUtf8(""))
        self.deparg.addItem(_fromUtf8(""))
        self.deparg.addItem(_fromUtf8(""))
        self.deparg.addItem(_fromUtf8(""))
        self.deparg.addItem(_fromUtf8(""))
        self.formLayout_4.setWidget(2, QtGui.QFormLayout.FieldRole, self.deparg)
        self.polar = QtGui.QComboBox(self.formLayoutWidget_4)
        self.polar.setObjectName(_fromUtf8("polar"))
        self.polar.addItem(_fromUtf8(""))
        self.polar.addItem(_fromUtf8(""))
        self.polar.addItem(_fromUtf8(""))
        self.polar.addItem(_fromUtf8(""))
        self.polar.addItem(_fromUtf8(""))
        self.polar.addItem(_fromUtf8(""))
        self.polar.addItem(_fromUtf8(""))
        self.formLayout_4.setWidget(0, QtGui.QFormLayout.FieldRole, self.polar)
        self.tableWidget = QtGui.QTableWidget(Form)
        self.tableWidget.setGeometry(QtCore.QRect(50, 250, 271, 321))
        self.tableWidget.setObjectName(_fromUtf8("tableWidget"))
        self.tableWidget.setColumnCount(1)
        self.tableWidget.setRowCount(10)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(6, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(7, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(8, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(9, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        self.graphicsView = QtGui.QGraphicsView(Form)
        self.graphicsView.setGeometry(QtCore.QRect(360, 370, 421, 192))
        self.graphicsView.setObjectName(_fromUtf8("graphicsView"))
        self.status = QtGui.QTextEdit(Form)
        self.status.setGeometry(QtCore.QRect(360, 170, 181, 181))
        self.status.setObjectName(_fromUtf8("status"))
        self.analytic = QtGui.QTextEdit(Form)
        self.analytic.setGeometry(QtCore.QRect(570, 170, 211, 181))
        self.analytic.setObjectName(_fromUtf8("analytic"))
        self.label = QtGui.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(430, 150, 71, 16))
        self.label.setObjectName(_fromUtf8("label"))
        self.label_2 = QtGui.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(620, 150, 161, 16))
        self.label_2.setObjectName(_fromUtf8("label_2"))

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(_translate("Form", "Form", None))
        self.sim.setText(_translate("Form", "Simulate", None))
        self.beam.setText(_translate("Form", "Beam", None))
        self.undulator.setText(_translate("Form", "Undulator", None))
        self.precision.setText(_translate("Form", "Precision", None))
        self.plot.setText(_translate("Form", "Plot", None))
        self.label_31.setText(_translate("Form", "Polarization", None))
        self.label_32.setText(_translate("Form", "Intensity", None))
        self.intesity.setItemText(0, _translate("Form", "Single Electron Intensity", None))
        self.intesity.setItemText(1, _translate("Form", "Multi Electron Intensity", None))
        self.intesity.setItemText(2, _translate("Form", "Single Electron Flux", None))
        self.intesity.setItemText(3, _translate("Form", "Multi Electron Flux", None))
        self.intesity.setItemText(4, _translate("Form", "Single Electron Radiation Phase", None))
        self.intesity.setItemText(5, _translate("Form", "Real Part of Electron E-Field", None))
        self.intesity.setItemText(6, _translate("Form", "Imaginary Part of Electron E-Field", None))
        self.label_33.setText(_translate("Form", "Dependent Argument", None))
        self.deparg.setItemText(0, _translate("Form", "e (energy)", None))
        self.deparg.setItemText(1, _translate("Form", "x (horizontal)", None))
        self.deparg.setItemText(2, _translate("Form", "y (vertical)", None))
        self.deparg.setItemText(3, _translate("Form", "x & y", None))
        self.deparg.setItemText(4, _translate("Form", "e & x", None))
        self.deparg.setItemText(5, _translate("Form", "e & y", None))
        self.deparg.setItemText(6, _translate("Form", "e & x & y", None))
        self.polar.setItemText(0, _translate("Form", "Linear Horizontal", None))
        self.polar.setItemText(1, _translate("Form", "Linear Vertical", None))
        self.polar.setItemText(2, _translate("Form", "Linear 45 Degrees", None))
        self.polar.setItemText(3, _translate("Form", "Linear 135 Degrees", None))
        self.polar.setItemText(4, _translate("Form", "Circular Right", None))
        self.polar.setItemText(5, _translate("Form", "Circular", None))
        self.polar.setItemText(6, _translate("Form", "Total", None))
        item = self.tableWidget.verticalHeaderItem(0)
        item.setText(_translate("Form", "Number of points along Energy", None))
        item = self.tableWidget.verticalHeaderItem(1)
        item.setText(_translate("Form", "Number of points along X", None))
        item = self.tableWidget.verticalHeaderItem(2)
        item.setText(_translate("Form", "Number of points along Y", None))
        item = self.tableWidget.verticalHeaderItem(3)
        item.setText(_translate("Form", "Positin to calculate SR", None))
        item = self.tableWidget.verticalHeaderItem(4)
        item.setText(_translate("Form", "Inital Photon Energy", None))
        item = self.tableWidget.verticalHeaderItem(5)
        item.setText(_translate("Form", "Final Photon Energy", None))
        item = self.tableWidget.verticalHeaderItem(6)
        item.setText(_translate("Form", "Inital X position", None))
        item = self.tableWidget.verticalHeaderItem(7)
        item.setText(_translate("Form", "Inital Y position", None))
        item = self.tableWidget.verticalHeaderItem(8)
        item.setText(_translate("Form", "Final X position", None))
        item = self.tableWidget.verticalHeaderItem(9)
        item.setText(_translate("Form", "Final Y position", None))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Form", "Mesh", None))
        self.label.setText(_translate("Form", "Status", None))
        self.label_2.setText(_translate("Form", "Analytic Calculations", None))

