# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ploading.ui'
#
# Created: Tue Jan 13 16:18:18 2015
#      by: pyside-uic 0.2.14 running on PySide 1.1.2
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_ploading(object):
    def setupUi(self, ploading):
        ploading.setObjectName("ploading")
        ploading.resize(281, 412)
        self.formLayoutWidget = QtGui.QWidget(ploading)
        self.formLayoutWidget.setGeometry(QtCore.QRect(30, 250, 221, 131))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtGui.QFormLayout(self.formLayoutWidget)
        self.formLayout.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.label = QtGui.QLabel(self.formLayoutWidget)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.label)
        self.itgaus = QtGui.QComboBox(self.formLayoutWidget)
        self.itgaus.setObjectName("itgaus")
        self.itgaus.addItem("")
        self.itgaus.addItem("")
        self.itgaus.addItem("")
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.itgaus)
        self.label_2 = QtGui.QLabel(self.formLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_2)
        self.itgamgaus = QtGui.QComboBox(self.formLayoutWidget)
        self.itgamgaus.setObjectName("itgamgaus")
        self.itgamgaus.addItem("")
        self.itgamgaus.addItem("")
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.itgamgaus)
        self.label_3 = QtGui.QLabel(self.formLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_3)
        self.iall = QtGui.QLineEdit(self.formLayoutWidget)
        self.iall.setObjectName("iall")
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.iall)
        self.label_4 = QtGui.QLabel(self.formLayoutWidget)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(3, QtGui.QFormLayout.LabelRole, self.label_4)
        self.label_5 = QtGui.QLabel(self.formLayoutWidget)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(4, QtGui.QFormLayout.LabelRole, self.label_5)
        self.ipspeed = QtGui.QLineEdit(self.formLayoutWidget)
        self.ipspeed.setObjectName("ipspeed")
        self.formLayout.setWidget(3, QtGui.QFormLayout.FieldRole, self.ipspeed)
        self.nbins = QtGui.QLineEdit(self.formLayoutWidget)
        self.nbins.setObjectName("nbins")
        self.formLayout.setWidget(4, QtGui.QFormLayout.FieldRole, self.nbins)
        self.tableWidget = QtGui.QTableWidget(ploading)
        self.tableWidget.setGeometry(QtCore.QRect(30, 30, 221, 211))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(1)
        self.tableWidget.setRowCount(6)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)

        self.retranslateUi(ploading)
        QtCore.QMetaObject.connectSlotsByName(ploading)

    def retranslateUi(self, ploading):
        ploading.setWindowTitle(QtGui.QApplication.translate("ploading", "Form", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("ploading", "Distribution Profile:", None, QtGui.QApplication.UnicodeUTF8))
        self.itgaus.setItemText(0, QtGui.QApplication.translate("ploading", "Gaussian", None, QtGui.QApplication.UnicodeUTF8))
        self.itgaus.setItemText(1, QtGui.QApplication.translate("ploading", "Uniform", None, QtGui.QApplication.UnicodeUTF8))
        self.itgaus.setItemText(2, QtGui.QApplication.translate("ploading", "Parabolic", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("ploading", "Energy Profile:", None, QtGui.QApplication.UnicodeUTF8))
        self.itgamgaus.setItemText(0, QtGui.QApplication.translate("ploading", "Gaussian", None, QtGui.QApplication.UnicodeUTF8))
        self.itgamgaus.setItemText(1, QtGui.QApplication.translate("ploading", "Uniform", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("ploading", "IALL:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("ploading", "IPSEED:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("ploading", "NBINS:", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget.verticalHeaderItem(0).setText(QtGui.QApplication.translate("ploading", "particle phase", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget.verticalHeaderItem(1).setText(QtGui.QApplication.translate("ploading", "energy distribution", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget.verticalHeaderItem(2).setText(QtGui.QApplication.translate("ploading", "x", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget.verticalHeaderItem(3).setText(QtGui.QApplication.translate("ploading", "y", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget.verticalHeaderItem(4).setText(QtGui.QApplication.translate("ploading", "px", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget.verticalHeaderItem(5).setText(QtGui.QApplication.translate("ploading", "py", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget.horizontalHeaderItem(0).setText(QtGui.QApplication.translate("ploading", "Hammersley Base", None, QtGui.QApplication.UnicodeUTF8))

