# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'radtrack/ui/rbele.ui'
#
# Created: Fri May 20 05:16:48 2016
#      by: PyQt4 UI code generator 4.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_ELE(object):
    def setupUi(self, ELE):
        ELE.setObjectName(_fromUtf8("ELE"))
        ELE.resize(1061, 500)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(ELE.sizePolicy().hasHeightForWidth())
        ELE.setSizePolicy(sizePolicy)
        self.gridLayout = QtGui.QGridLayout(ELE)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.splitter = QtGui.QSplitter(ELE)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.splitter.sizePolicy().hasHeightForWidth())
        self.splitter.setSizePolicy(sizePolicy)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName(_fromUtf8("splitter"))
        self.layoutWidget = QtGui.QWidget(self.splitter)
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_3.setMargin(0)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.simulationStatusLabel = QtGui.QLabel(self.layoutWidget)
        self.simulationStatusLabel.setEnabled(False)
        self.simulationStatusLabel.setStyleSheet(_fromUtf8("QLabel {font-weight: bold}"))
        self.simulationStatusLabel.setObjectName(_fromUtf8("simulationStatusLabel"))
        self.verticalLayout_3.addWidget(self.simulationStatusLabel)
        self.line_3 = QtGui.QFrame(self.layoutWidget)
        self.line_3.setFrameShape(QtGui.QFrame.HLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName(_fromUtf8("line_3"))
        self.verticalLayout_3.addWidget(self.line_3)
        self.simulationStatusTextEdit = QtGui.QTextEdit(self.layoutWidget)
        self.simulationStatusTextEdit.setEnabled(False)
        self.simulationStatusTextEdit.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.simulationStatusTextEdit.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.simulationStatusTextEdit.setReadOnly(True)
        self.simulationStatusTextEdit.setObjectName(_fromUtf8("simulationStatusTextEdit"))
        self.verticalLayout_3.addWidget(self.simulationStatusTextEdit)
        self.layoutWidget1 = QtGui.QWidget(self.splitter)
        self.layoutWidget1.setObjectName(_fromUtf8("layoutWidget1"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout_2.setMargin(0)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.simulationResultsLabel = QtGui.QLabel(self.layoutWidget1)
        self.simulationResultsLabel.setEnabled(False)
        self.simulationResultsLabel.setStyleSheet(_fromUtf8("QLabel {font-weight: bold}"))
        self.simulationResultsLabel.setObjectName(_fromUtf8("simulationResultsLabel"))
        self.verticalLayout_2.addWidget(self.simulationResultsLabel)
        self.line_4 = QtGui.QFrame(self.layoutWidget1)
        self.line_4.setFrameShape(QtGui.QFrame.HLine)
        self.line_4.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_4.setObjectName(_fromUtf8("line_4"))
        self.verticalLayout_2.addWidget(self.line_4)
        self.simulationResultsListWidget = QtGui.QListWidget(self.layoutWidget1)
        self.simulationResultsListWidget.setEnabled(False)
        self.simulationResultsListWidget.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.simulationResultsListWidget.setObjectName(_fromUtf8("simulationResultsListWidget"))
        self.verticalLayout_2.addWidget(self.simulationResultsListWidget)
        self.gridLayout.addWidget(self.splitter, 0, 1, 1, 1)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.parametersLabel = QtGui.QLabel(ELE)
        self.parametersLabel.setStyleSheet(_fromUtf8("QLabel {font-weight:bold}"))
        self.parametersLabel.setObjectName(_fromUtf8("parametersLabel"))
        self.verticalLayout.addWidget(self.parametersLabel)
        self.line_2 = QtGui.QFrame(ELE)
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.verticalLayout.addWidget(self.line_2)
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem, 11, 0, 1, 1)
        self.simulateButton = QtGui.QPushButton(ELE)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.simulateButton.sizePolicy().hasHeightForWidth())
        self.simulateButton.setSizePolicy(sizePolicy)
        self.simulateButton.setObjectName(_fromUtf8("simulateButton"))
        self.gridLayout_2.addWidget(self.simulateButton, 9, 0, 1, 1)
        self.abortButton = QtGui.QPushButton(ELE)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.abortButton.sizePolicy().hasHeightForWidth())
        self.abortButton.setSizePolicy(sizePolicy)
        self.abortButton.setObjectName(_fromUtf8("abortButton"))
        self.gridLayout_2.addWidget(self.abortButton, 9, 1, 1, 1)
        self.momentumLabel = QtGui.QLabel(ELE)
        self.momentumLabel.setObjectName(_fromUtf8("momentumLabel"))
        self.gridLayout_2.addWidget(self.momentumLabel, 3, 0, 1, 1)
        self.momentumLineEdit = QtGui.QLineEdit(ELE)
        self.momentumLineEdit.setObjectName(_fromUtf8("momentumLineEdit"))
        self.gridLayout_2.addWidget(self.momentumLineEdit, 3, 1, 1, 1)
        self.beamLineLabel = QtGui.QLabel(ELE)
        self.beamLineLabel.setEnabled(True)
        self.beamLineLabel.setObjectName(_fromUtf8("beamLineLabel"))
        self.gridLayout_2.addWidget(self.beamLineLabel, 2, 0, 1, 1)
        self.beamLineComboBox = QtGui.QComboBox(ELE)
        self.beamLineComboBox.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.beamLineComboBox.sizePolicy().hasHeightForWidth())
        self.beamLineComboBox.setSizePolicy(sizePolicy)
        self.beamLineComboBox.setObjectName(_fromUtf8("beamLineComboBox"))
        self.gridLayout_2.addWidget(self.beamLineComboBox, 2, 1, 1, 1)
        self.beamLineSourceComboBox = QtGui.QComboBox(ELE)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.beamLineSourceComboBox.sizePolicy().hasHeightForWidth())
        self.beamLineSourceComboBox.setSizePolicy(sizePolicy)
        self.beamLineSourceComboBox.setObjectName(_fromUtf8("beamLineSourceComboBox"))
        self.gridLayout_2.addWidget(self.beamLineSourceComboBox, 1, 1, 1, 1)
        self.beamLineSourceLabel = QtGui.QLabel(ELE)
        self.beamLineSourceLabel.setObjectName(_fromUtf8("beamLineSourceLabel"))
        self.gridLayout_2.addWidget(self.beamLineSourceLabel, 1, 0, 1, 1)
        self.bunchSourceComboBox = QtGui.QComboBox(ELE)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bunchSourceComboBox.sizePolicy().hasHeightForWidth())
        self.bunchSourceComboBox.setSizePolicy(sizePolicy)
        self.bunchSourceComboBox.setObjectName(_fromUtf8("bunchSourceComboBox"))
        self.gridLayout_2.addWidget(self.bunchSourceComboBox, 0, 1, 1, 1)
        self.bunchSourceLabel = QtGui.QLabel(ELE)
        self.bunchSourceLabel.setObjectName(_fromUtf8("bunchSourceLabel"))
        self.gridLayout_2.addWidget(self.bunchSourceLabel, 0, 0, 1, 1)
        self.numProcLabel = QtGui.QLabel(ELE)
        self.numProcLabel.setObjectName(_fromUtf8("numProcLabel"))
        self.gridLayout_2.addWidget(self.numProcLabel, 7, 0, 1, 1)
        self.progressBar = QtGui.QProgressBar(ELE)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setTextVisible(True)
        self.progressBar.setInvertedAppearance(False)
        self.progressBar.setObjectName(_fromUtf8("progressBar"))
        self.gridLayout_2.addWidget(self.progressBar, 10, 0, 1, 2)
        self.run_in_parallel = QtGui.QCheckBox(ELE)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.run_in_parallel.sizePolicy().hasHeightForWidth())
        self.run_in_parallel.setSizePolicy(sizePolicy)
        self.run_in_parallel.setMinimumSize(QtCore.QSize(20, 20))
        self.run_in_parallel.setObjectName(_fromUtf8("run_in_parallel"))
        self.gridLayout_2.addWidget(self.run_in_parallel, 6, 1, 1, 1)
        self.numProcSlider = QtGui.QSlider(ELE)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.numProcSlider.sizePolicy().hasHeightForWidth())
        self.numProcSlider.setSizePolicy(sizePolicy)
        self.numProcSlider.setMinimumSize(QtCore.QSize(40, 20))
        self.numProcSlider.setMinimum(2)
        self.numProcSlider.setMaximum(4)
        self.numProcSlider.setPageStep(2)
        self.numProcSlider.setProperty("value", 2)
        self.numProcSlider.setOrientation(QtCore.Qt.Horizontal)
        self.numProcSlider.setTickInterval(1)
        self.numProcSlider.setObjectName(_fromUtf8("numProcSlider"))
        self.gridLayout_2.addWidget(self.numProcSlider, 7, 1, 1, 1)
        self.particleLabel = QtGui.QLabel(ELE)
        self.particleLabel.setObjectName(_fromUtf8("particleLabel"))
        self.gridLayout_2.addWidget(self.particleLabel, 4, 0, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(20, 30, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.gridLayout_2.addItem(spacerItem1, 8, 0, 1, 1)
        self.particleComboBox = QtGui.QComboBox(ELE)
        self.particleComboBox.setObjectName(_fromUtf8("particleComboBox"))
        self.particleComboBox.addItem(_fromUtf8(""))
        self.particleComboBox.addItem(_fromUtf8(""))
        self.gridLayout_2.addWidget(self.particleComboBox, 4, 1, 1, 1)
        spacerItem2 = QtGui.QSpacerItem(20, 30, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.gridLayout_2.addItem(spacerItem2, 5, 0, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_2)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)
        self.momentumLabel.setBuddy(self.momentumLineEdit)
        self.beamLineLabel.setBuddy(self.beamLineComboBox)
        self.beamLineSourceLabel.setBuddy(self.beamLineSourceComboBox)
        self.bunchSourceLabel.setBuddy(self.bunchSourceComboBox)
        self.numProcLabel.setBuddy(self.numProcSlider)
        self.particleLabel.setBuddy(self.particleComboBox)

        self.retranslateUi(ELE)
        QtCore.QMetaObject.connectSlotsByName(ELE)
        ELE.setTabOrder(self.bunchSourceComboBox, self.beamLineSourceComboBox)
        ELE.setTabOrder(self.beamLineSourceComboBox, self.beamLineComboBox)
        ELE.setTabOrder(self.beamLineComboBox, self.momentumLineEdit)
        ELE.setTabOrder(self.momentumLineEdit, self.particleComboBox)
        ELE.setTabOrder(self.particleComboBox, self.run_in_parallel)
        ELE.setTabOrder(self.run_in_parallel, self.numProcSlider)
        ELE.setTabOrder(self.numProcSlider, self.simulateButton)
        ELE.setTabOrder(self.simulateButton, self.abortButton)
        ELE.setTabOrder(self.abortButton, self.simulationStatusTextEdit)
        ELE.setTabOrder(self.simulationStatusTextEdit, self.simulationResultsListWidget)

    def retranslateUi(self, ELE):
        ELE.setWindowTitle(_translate("ELE", "Form", None))
        self.simulationStatusLabel.setText(_translate("ELE", "Simulation Status", None))
        self.simulationResultsLabel.setText(_translate("ELE", "Simulation Results", None))
        self.simulationResultsListWidget.setToolTip(_translate("ELE", "Right-click to open the selected files.", None))
        self.parametersLabel.setText(_translate("ELE", "Parameters", None))
        self.simulateButton.setText(_translate("ELE", "Simulate", None))
        self.abortButton.setText(_translate("ELE", "Abort", None))
        self.momentumLabel.setText(_translate("ELE", "Momentum:", None))
        self.beamLineLabel.setText(_translate("ELE", "Beam Line:", None))
        self.beamLineSourceLabel.setText(_translate("ELE", "Beam Line Source:", None))
        self.bunchSourceLabel.setText(_translate("ELE", "Bunch Source:", None))
        self.numProcLabel.setText(_translate("ELE", "Number of Processes: 2  ", None))
        self.run_in_parallel.setText(_translate("ELE", "Run in parallel", None))
        self.particleLabel.setText(_translate("ELE", "Particle Type:", None))
        self.particleComboBox.setItemText(0, _translate("ELE", "electron", None))
        self.particleComboBox.setItemText(1, _translate("ELE", "proton", None))

