# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'radtrack/ui/rbele.ui'
#
# Created: Fri May 27 01:11:58 2016
#      by: PyQt4 UI code generator 4.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_ELE(object):
    def setupUi(self, ELE):
        ELE.setObjectName(_fromUtf8("ELE"))
        ELE.resize(1061, 500)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(ELE.sizePolicy().hasHeightForWidth())
        ELE.setSizePolicy(sizePolicy)
        self.horizontalLayout = QtGui.QHBoxLayout(ELE)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.splitter = QtGui.QSplitter(ELE)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setChildrenCollapsible(False)
        self.splitter.setObjectName(_fromUtf8("splitter"))
        self.layoutWidget_2 = QtGui.QWidget(self.splitter)
        self.layoutWidget_2.setObjectName(_fromUtf8("layoutWidget_2"))
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.layoutWidget_2)
        self.verticalLayout_6.setMargin(0)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.parametersLabel = QtGui.QLabel(self.layoutWidget_2)
        self.parametersLabel.setStyleSheet(_fromUtf8("QLabel {font-weight:bold}"))
        self.parametersLabel.setObjectName(_fromUtf8("parametersLabel"))
        self.verticalLayout_6.addWidget(self.parametersLabel)
        self.line = QtGui.QFrame(self.layoutWidget_2)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.verticalLayout_6.addWidget(self.line)
        self.elegantEditStackedWidget = QtGui.QStackedWidget(self.layoutWidget_2)
        self.elegantEditStackedWidget.setObjectName(_fromUtf8("elegantEditStackedWidget"))
        self.simpleElegantParameters = QtGui.QWidget()
        self.simpleElegantParameters.setObjectName(_fromUtf8("simpleElegantParameters"))
        self.gridLayout_6 = QtGui.QGridLayout(self.simpleElegantParameters)
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.beamLineComboBox = QtGui.QComboBox(self.simpleElegantParameters)
        self.beamLineComboBox.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.beamLineComboBox.sizePolicy().hasHeightForWidth())
        self.beamLineComboBox.setSizePolicy(sizePolicy)
        self.beamLineComboBox.setObjectName(_fromUtf8("beamLineComboBox"))
        self.gridLayout_6.addWidget(self.beamLineComboBox, 4, 1, 1, 1)
        self.beamLineSourceComboBox = QtGui.QComboBox(self.simpleElegantParameters)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.beamLineSourceComboBox.sizePolicy().hasHeightForWidth())
        self.beamLineSourceComboBox.setSizePolicy(sizePolicy)
        self.beamLineSourceComboBox.setObjectName(_fromUtf8("beamLineSourceComboBox"))
        self.gridLayout_6.addWidget(self.beamLineSourceComboBox, 3, 1, 1, 1)
        self.bunchSourceLabel = QtGui.QLabel(self.simpleElegantParameters)
        self.bunchSourceLabel.setObjectName(_fromUtf8("bunchSourceLabel"))
        self.gridLayout_6.addWidget(self.bunchSourceLabel, 2, 0, 1, 1)
        self.bunchSourceComboBox = QtGui.QComboBox(self.simpleElegantParameters)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bunchSourceComboBox.sizePolicy().hasHeightForWidth())
        self.bunchSourceComboBox.setSizePolicy(sizePolicy)
        self.bunchSourceComboBox.setObjectName(_fromUtf8("bunchSourceComboBox"))
        self.gridLayout_6.addWidget(self.bunchSourceComboBox, 2, 1, 1, 1)
        self.beamLineLabel = QtGui.QLabel(self.simpleElegantParameters)
        self.beamLineLabel.setEnabled(True)
        self.beamLineLabel.setObjectName(_fromUtf8("beamLineLabel"))
        self.gridLayout_6.addWidget(self.beamLineLabel, 4, 0, 1, 1)
        self.beamLineSourceLabel = QtGui.QLabel(self.simpleElegantParameters)
        self.beamLineSourceLabel.setObjectName(_fromUtf8("beamLineSourceLabel"))
        self.gridLayout_6.addWidget(self.beamLineSourceLabel, 3, 0, 1, 1)
        self.momentumLineEdit = QtGui.QLineEdit(self.simpleElegantParameters)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.momentumLineEdit.sizePolicy().hasHeightForWidth())
        self.momentumLineEdit.setSizePolicy(sizePolicy)
        self.momentumLineEdit.setObjectName(_fromUtf8("momentumLineEdit"))
        self.gridLayout_6.addWidget(self.momentumLineEdit, 5, 1, 1, 1)
        self.particleLabel = QtGui.QLabel(self.simpleElegantParameters)
        self.particleLabel.setObjectName(_fromUtf8("particleLabel"))
        self.gridLayout_6.addWidget(self.particleLabel, 6, 0, 1, 1)
        self.particleComboBox = QtGui.QComboBox(self.simpleElegantParameters)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.particleComboBox.sizePolicy().hasHeightForWidth())
        self.particleComboBox.setSizePolicy(sizePolicy)
        self.particleComboBox.setObjectName(_fromUtf8("particleComboBox"))
        self.particleComboBox.addItem(_fromUtf8(""))
        self.particleComboBox.addItem(_fromUtf8(""))
        self.gridLayout_6.addWidget(self.particleComboBox, 6, 1, 1, 1)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_6.addItem(spacerItem, 8, 0, 1, 1)
        self.momentumLabel = QtGui.QLabel(self.simpleElegantParameters)
        self.momentumLabel.setObjectName(_fromUtf8("momentumLabel"))
        self.gridLayout_6.addWidget(self.momentumLabel, 5, 0, 1, 1)
        self.simpleParamsToEleButton = QtGui.QPushButton(self.simpleElegantParameters)
        self.simpleParamsToEleButton.setObjectName(_fromUtf8("simpleParamsToEleButton"))
        self.gridLayout_6.addWidget(self.simpleParamsToEleButton, 7, 0, 1, 2)
        self.elegantEditStackedWidget.addWidget(self.simpleElegantParameters)
        self.elegantFileEditor = QtGui.QWidget()
        self.elegantFileEditor.setObjectName(_fromUtf8("elegantFileEditor"))
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.elegantFileEditor)
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.elegantTextEdit = QtGui.QPlainTextEdit(self.elegantFileEditor)
        self.elegantTextEdit.setObjectName(_fromUtf8("elegantTextEdit"))
        self.verticalLayout_7.addWidget(self.elegantTextEdit)
        self.elegantEditStackedWidget.addWidget(self.elegantFileEditor)
        self.verticalLayout_6.addWidget(self.elegantEditStackedWidget)
        self.elegantEditToggleButton = QtGui.QPushButton(self.layoutWidget_2)
        self.elegantEditToggleButton.setObjectName(_fromUtf8("elegantEditToggleButton"))
        self.verticalLayout_6.addWidget(self.elegantEditToggleButton)
        self.gridLayout_4 = QtGui.QGridLayout()
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.abortButton = QtGui.QPushButton(self.layoutWidget_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.abortButton.sizePolicy().hasHeightForWidth())
        self.abortButton.setSizePolicy(sizePolicy)
        self.abortButton.setObjectName(_fromUtf8("abortButton"))
        self.gridLayout_4.addWidget(self.abortButton, 2, 1, 1, 1)
        self.run_in_parallel = QtGui.QCheckBox(self.layoutWidget_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.run_in_parallel.sizePolicy().hasHeightForWidth())
        self.run_in_parallel.setSizePolicy(sizePolicy)
        self.run_in_parallel.setMinimumSize(QtCore.QSize(20, 20))
        self.run_in_parallel.setObjectName(_fromUtf8("run_in_parallel"))
        self.gridLayout_4.addWidget(self.run_in_parallel, 0, 0, 1, 1)
        self.simulateButton = QtGui.QPushButton(self.layoutWidget_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.simulateButton.sizePolicy().hasHeightForWidth())
        self.simulateButton.setSizePolicy(sizePolicy)
        self.simulateButton.setObjectName(_fromUtf8("simulateButton"))
        self.gridLayout_4.addWidget(self.simulateButton, 2, 0, 1, 1)
        self.numProcLabel = QtGui.QLabel(self.layoutWidget_2)
        self.numProcLabel.setObjectName(_fromUtf8("numProcLabel"))
        self.gridLayout_4.addWidget(self.numProcLabel, 1, 0, 1, 1)
        self.numProcSlider = QtGui.QSlider(self.layoutWidget_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.numProcSlider.sizePolicy().hasHeightForWidth())
        self.numProcSlider.setSizePolicy(sizePolicy)
        self.numProcSlider.setMinimumSize(QtCore.QSize(40, 20))
        self.numProcSlider.setMinimum(2)
        self.numProcSlider.setMaximum(4)
        self.numProcSlider.setPageStep(2)
        self.numProcSlider.setProperty("value", 2)
        self.numProcSlider.setOrientation(QtCore.Qt.Horizontal)
        self.numProcSlider.setTickInterval(1)
        self.numProcSlider.setObjectName(_fromUtf8("numProcSlider"))
        self.gridLayout_4.addWidget(self.numProcSlider, 1, 1, 1, 1)
        self.progressBar = QtGui.QProgressBar(self.layoutWidget_2)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setTextVisible(True)
        self.progressBar.setInvertedAppearance(False)
        self.progressBar.setObjectName(_fromUtf8("progressBar"))
        self.gridLayout_4.addWidget(self.progressBar, 3, 0, 1, 2)
        self.verticalLayout_6.addLayout(self.gridLayout_4)
        self.layoutWidget = QtGui.QWidget(self.splitter)
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_3.setMargin(0)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.simulationStatusLabel = QtGui.QLabel(self.layoutWidget)
        self.simulationStatusLabel.setEnabled(False)
        self.simulationStatusLabel.setStyleSheet(_fromUtf8("QLabel {font-weight: bold}"))
        self.simulationStatusLabel.setObjectName(_fromUtf8("simulationStatusLabel"))
        self.verticalLayout_3.addWidget(self.simulationStatusLabel)
        self.line_3 = QtGui.QFrame(self.layoutWidget)
        self.line_3.setFrameShape(QtGui.QFrame.HLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName(_fromUtf8("line_3"))
        self.verticalLayout_3.addWidget(self.line_3)
        self.simulationStatusTextEdit = QtGui.QTextEdit(self.layoutWidget)
        self.simulationStatusTextEdit.setEnabled(False)
        self.simulationStatusTextEdit.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.simulationStatusTextEdit.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.simulationStatusTextEdit.setReadOnly(True)
        self.simulationStatusTextEdit.setObjectName(_fromUtf8("simulationStatusTextEdit"))
        self.verticalLayout_3.addWidget(self.simulationStatusTextEdit)
        self.layoutWidget1 = QtGui.QWidget(self.splitter)
        self.layoutWidget1.setObjectName(_fromUtf8("layoutWidget1"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout_2.setMargin(0)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.simulationResultsLabel = QtGui.QLabel(self.layoutWidget1)
        self.simulationResultsLabel.setEnabled(False)
        self.simulationResultsLabel.setStyleSheet(_fromUtf8("QLabel {font-weight: bold}"))
        self.simulationResultsLabel.setObjectName(_fromUtf8("simulationResultsLabel"))
        self.verticalLayout_2.addWidget(self.simulationResultsLabel)
        self.line_4 = QtGui.QFrame(self.layoutWidget1)
        self.line_4.setFrameShape(QtGui.QFrame.HLine)
        self.line_4.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_4.setObjectName(_fromUtf8("line_4"))
        self.verticalLayout_2.addWidget(self.line_4)
        self.simulationResultsListWidget = QtGui.QListWidget(self.layoutWidget1)
        self.simulationResultsListWidget.setEnabled(False)
        self.simulationResultsListWidget.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.simulationResultsListWidget.setObjectName(_fromUtf8("simulationResultsListWidget"))
        self.verticalLayout_2.addWidget(self.simulationResultsListWidget)
        self.horizontalLayout.addWidget(self.splitter)
        self.bunchSourceLabel.setBuddy(self.bunchSourceComboBox)
        self.beamLineLabel.setBuddy(self.beamLineComboBox)
        self.beamLineSourceLabel.setBuddy(self.beamLineSourceComboBox)
        self.particleLabel.setBuddy(self.particleComboBox)
        self.momentumLabel.setBuddy(self.momentumLineEdit)
        self.numProcLabel.setBuddy(self.numProcSlider)

        self.retranslateUi(ELE)
        self.elegantEditStackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(ELE)
        ELE.setTabOrder(self.simulationStatusTextEdit, self.simulationResultsListWidget)

    def retranslateUi(self, ELE):
        ELE.setWindowTitle(_translate("ELE", "Form", None))
        self.parametersLabel.setText(_translate("ELE", "Simple Parameter Input", None))
        self.bunchSourceLabel.setText(_translate("ELE", "Bunch Source:", None))
        self.beamLineLabel.setText(_translate("ELE", "Beam Line:", None))
        self.beamLineSourceLabel.setText(_translate("ELE", "Beam Line Source:", None))
        self.particleLabel.setText(_translate("ELE", "Particle Type:", None))
        self.particleComboBox.setItemText(0, _translate("ELE", "electron", None))
        self.particleComboBox.setItemText(1, _translate("ELE", "proton", None))
        self.momentumLabel.setText(_translate("ELE", "Momentum:", None))
        self.simpleParamsToEleButton.setText(_translate("ELE", "Create ELE file and edit", None))
        self.elegantEditToggleButton.setText(_translate("ELE", "Edit Elegant File", None))
        self.abortButton.setText(_translate("ELE", "Abort", None))
        self.run_in_parallel.setText(_translate("ELE", "Run in parallel", None))
        self.simulateButton.setText(_translate("ELE", "Simulate", None))
        self.numProcLabel.setText(_translate("ELE", "Number of Processes: 2  ", None))
        self.simulationStatusLabel.setText(_translate("ELE", "Simulation Status", None))
        self.simulationResultsLabel.setText(_translate("ELE", "Simulation Results", None))
        self.simulationResultsListWidget.setToolTip(_translate("ELE", "Right-click to open the selected files.", None))

