# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mxcal.ui'
#
# Created: Thu Nov 20 18:11:19 2014
#      by: pyside-uic 0.2.14 running on PySide 1.1.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1186, 552)
        self.gridLayout = QtGui.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtGui.QLabel(Form)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.line = QtGui.QFrame(Form)
        self.line.setFrameShape(QtGui.QFrame.VLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout.addWidget(self.line, 0, 1, 3, 1)
        self.label_12 = QtGui.QLabel(Form)
        self.label_12.setObjectName("label_12")
        self.gridLayout.addWidget(self.label_12, 0, 3, 1, 1)
        self.line_2 = QtGui.QFrame(Form)
        self.line_2.setFrameShape(QtGui.QFrame.VLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.gridLayout.addWidget(self.line_2, 0, 4, 16, 1)
        self.label_26 = QtGui.QLabel(Form)
        self.label_26.setObjectName("label_26")
        self.gridLayout.addWidget(self.label_26, 0, 6, 1, 2)
        self.widget = matplotlibWidget(Form)
        self.widget.setObjectName("widget")
        self.gridLayout.addWidget(self.widget, 0, 9, 6, 5)
        self.formLayout = QtGui.QFormLayout()
        self.formLayout.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setObjectName("formLayout")
        self.label_2 = QtGui.QLabel(Form)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_2)
        self.charge = QtGui.QLineEdit(Form)
        self.charge.setObjectName("charge")
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.charge)
        self.label_3 = QtGui.QLabel(Form)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_3)
        self.slicemit = QtGui.QLineEdit(Form)
        self.slicemit.setObjectName("slicemit")
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.slicemit)
        self.label_4 = QtGui.QLabel(Form)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_4)
        self.ebeamenergy = QtGui.QLineEdit(Form)
        self.ebeamenergy.setObjectName("ebeamenergy")
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.ebeamenergy)
        self.label_5 = QtGui.QLabel(Form)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(3, QtGui.QFormLayout.LabelRole, self.label_5)
        self.energyspread = QtGui.QLineEdit(Form)
        self.energyspread.setObjectName("energyspread")
        self.formLayout.setWidget(3, QtGui.QFormLayout.FieldRole, self.energyspread)
        self.label_7 = QtGui.QLabel(Form)
        self.label_7.setObjectName("label_7")
        self.formLayout.setWidget(4, QtGui.QFormLayout.LabelRole, self.label_7)
        self.reprate = QtGui.QLineEdit(Form)
        self.reprate.setObjectName("reprate")
        self.formLayout.setWidget(4, QtGui.QFormLayout.FieldRole, self.reprate)
        self.label_17 = QtGui.QLabel(Form)
        self.label_17.setObjectName("label_17")
        self.formLayout.setWidget(5, QtGui.QFormLayout.LabelRole, self.label_17)
        self.peakamp = QtGui.QLineEdit(Form)
        self.peakamp.setStyleSheet("")
        self.peakamp.setReadOnly(True)
        self.peakamp.setObjectName("peakamp")
        self.formLayout.setWidget(5, QtGui.QFormLayout.FieldRole, self.peakamp)
        self.gridLayout.addLayout(self.formLayout, 1, 0, 2, 1)
        self.formLayout_3 = QtGui.QFormLayout()
        self.formLayout_3.setObjectName("formLayout_3")
        self.label_13 = QtGui.QLabel(Form)
        self.label_13.setObjectName("label_13")
        self.formLayout_3.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_13)
        self.bunlen = QtGui.QLineEdit(Form)
        self.bunlen.setStyleSheet("background-color: rgb(190, 190, 190);")
        self.bunlen.setReadOnly(True)
        self.bunlen.setObjectName("bunlen")
        self.formLayout_3.setWidget(0, QtGui.QFormLayout.FieldRole, self.bunlen)
        self.label_14 = QtGui.QLabel(Form)
        self.label_14.setObjectName("label_14")
        self.formLayout_3.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_14)
        self.gamma = QtGui.QLineEdit(Form)
        self.gamma.setStyleSheet("background-color: rgb(190, 190, 190);")
        self.gamma.setReadOnly(True)
        self.gamma.setObjectName("gamma")
        self.formLayout_3.setWidget(2, QtGui.QFormLayout.FieldRole, self.gamma)
        self.label_15 = QtGui.QLabel(Form)
        self.label_15.setObjectName("label_15")
        self.formLayout_3.setWidget(3, QtGui.QFormLayout.LabelRole, self.label_15)
        self.edensity = QtGui.QLineEdit(Form)
        self.edensity.setStyleSheet("background-color: rgb(190, 190, 190);")
        self.edensity.setReadOnly(True)
        self.edensity.setObjectName("edensity")
        self.formLayout_3.setWidget(3, QtGui.QFormLayout.FieldRole, self.edensity)
        self.label_16 = QtGui.QLabel(Form)
        self.label_16.setObjectName("label_16")
        self.formLayout_3.setWidget(4, QtGui.QFormLayout.LabelRole, self.label_16)
        self.geoemit = QtGui.QLineEdit(Form)
        self.geoemit.setStyleSheet("background-color: rgb(190, 190, 190);")
        self.geoemit.setReadOnly(True)
        self.geoemit.setObjectName("geoemit")
        self.formLayout_3.setWidget(4, QtGui.QFormLayout.FieldRole, self.geoemit)
        self.label_6 = QtGui.QLabel(Form)
        self.label_6.setObjectName("label_6")
        self.formLayout_3.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_6)
        self.bunchlen = QtGui.QLineEdit(Form)
        self.bunchlen.setStyleSheet("background-color: rgb(190, 190, 190);")
        self.bunchlen.setReadOnly(True)
        self.bunchlen.setObjectName("bunchlen")
        self.formLayout_3.setWidget(1, QtGui.QFormLayout.FieldRole, self.bunchlen)
        self.gridLayout.addLayout(self.formLayout_3, 1, 2, 1, 2)
        self.formLayout_6 = QtGui.QFormLayout()
        self.formLayout_6.setObjectName("formLayout_6")
        self.label_27 = QtGui.QLabel(Form)
        self.label_27.setObjectName("label_27")
        self.formLayout_6.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_27)
        self.raleigh = QtGui.QLineEdit(Form)
        self.raleigh.setStyleSheet("background-color: rgb(190, 190, 190);")
        self.raleigh.setReadOnly(True)
        self.raleigh.setObjectName("raleigh")
        self.formLayout_6.setWidget(0, QtGui.QFormLayout.FieldRole, self.raleigh)
        self.label_28 = QtGui.QLabel(Form)
        self.label_28.setObjectName("label_28")
        self.formLayout_6.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_28)
        self.photonemit = QtGui.QLineEdit(Form)
        self.photonemit.setStyleSheet("background-color: rgb(190, 190, 190);")
        self.photonemit.setReadOnly(True)
        self.photonemit.setObjectName("photonemit")
        self.formLayout_6.setWidget(1, QtGui.QFormLayout.FieldRole, self.photonemit)
        self.label_29 = QtGui.QLabel(Form)
        self.label_29.setObjectName("label_29")
        self.formLayout_6.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_29)
        self.fel_1d = QtGui.QLineEdit(Form)
        self.fel_1d.setStyleSheet("background-color: rgb(190, 190, 190);")
        self.fel_1d.setReadOnly(True)
        self.fel_1d.setObjectName("fel_1d")
        self.formLayout_6.setWidget(2, QtGui.QFormLayout.FieldRole, self.fel_1d)
        self.label_30 = QtGui.QLabel(Form)
        self.label_30.setObjectName("label_30")
        self.formLayout_6.setWidget(3, QtGui.QFormLayout.LabelRole, self.label_30)
        self.gain_1d = QtGui.QLineEdit(Form)
        self.gain_1d.setStyleSheet("background-color: rgb(190, 190, 190);\n"
"")
        self.gain_1d.setReadOnly(True)
        self.gain_1d.setObjectName("gain_1d")
        self.formLayout_6.setWidget(3, QtGui.QFormLayout.FieldRole, self.gain_1d)
        self.label_31 = QtGui.QLabel(Form)
        self.label_31.setObjectName("label_31")
        self.formLayout_6.setWidget(4, QtGui.QFormLayout.LabelRole, self.label_31)
        self.dfactor = QtGui.QLineEdit(Form)
        self.dfactor.setStyleSheet("background-color: rgb(190, 190, 190);")
        self.dfactor.setReadOnly(True)
        self.dfactor.setObjectName("dfactor")
        self.formLayout_6.setWidget(4, QtGui.QFormLayout.FieldRole, self.dfactor)
        self.label_32 = QtGui.QLabel(Form)
        self.label_32.setObjectName("label_32")
        self.formLayout_6.setWidget(5, QtGui.QFormLayout.LabelRole, self.label_32)
        self.efactor = QtGui.QLineEdit(Form)
        self.efactor.setStyleSheet("background-color: rgb(190, 190, 190);")
        self.efactor.setReadOnly(True)
        self.efactor.setObjectName("efactor")
        self.formLayout_6.setWidget(5, QtGui.QFormLayout.FieldRole, self.efactor)
        self.label_33 = QtGui.QLabel(Form)
        self.label_33.setObjectName("label_33")
        self.formLayout_6.setWidget(6, QtGui.QFormLayout.LabelRole, self.label_33)
        self.espreadfactor = QtGui.QLineEdit(Form)
        self.espreadfactor.setStyleSheet("background-color: rgb(190, 190, 190);")
        self.espreadfactor.setReadOnly(True)
        self.espreadfactor.setObjectName("espreadfactor")
        self.formLayout_6.setWidget(6, QtGui.QFormLayout.FieldRole, self.espreadfactor)
        self.label_34 = QtGui.QLabel(Form)
        self.label_34.setObjectName("label_34")
        self.formLayout_6.setWidget(9, QtGui.QFormLayout.LabelRole, self.label_34)
        self.threedfel = QtGui.QLineEdit(Form)
        self.threedfel.setStyleSheet("background-color: rgb(190, 190, 190);")
        self.threedfel.setReadOnly(True)
        self.threedfel.setObjectName("threedfel")
        self.formLayout_6.setWidget(9, QtGui.QFormLayout.FieldRole, self.threedfel)
        self.label_35 = QtGui.QLabel(Form)
        self.label_35.setObjectName("label_35")
        self.formLayout_6.setWidget(10, QtGui.QFormLayout.LabelRole, self.label_35)
        self.gain_3d = QtGui.QLineEdit(Form)
        self.gain_3d.setStyleSheet("background-color: rgb(190, 190, 190);")
        self.gain_3d.setReadOnly(True)
        self.gain_3d.setObjectName("gain_3d")
        self.formLayout_6.setWidget(10, QtGui.QFormLayout.FieldRole, self.gain_3d)
        self.label_36 = QtGui.QLabel(Form)
        self.label_36.setObjectName("label_36")
        self.formLayout_6.setWidget(11, QtGui.QFormLayout.LabelRole, self.label_36)
        self.total = QtGui.QLineEdit(Form)
        self.total.setStyleSheet("background-color: rgb(190, 190, 190);")
        self.total.setReadOnly(True)
        self.total.setObjectName("total")
        self.formLayout_6.setWidget(11, QtGui.QFormLayout.FieldRole, self.total)
        self.label_37 = QtGui.QLabel(Form)
        self.label_37.setObjectName("label_37")
        self.formLayout_6.setWidget(7, QtGui.QFormLayout.LabelRole, self.label_37)
        self.sasepower = QtGui.QLineEdit(Form)
        self.sasepower.setStyleSheet("background-color: rgb(190, 190, 190);")
        self.sasepower.setReadOnly(True)
        self.sasepower.setObjectName("sasepower")
        self.formLayout_6.setWidget(7, QtGui.QFormLayout.FieldRole, self.sasepower)
        self.label_38 = QtGui.QLabel(Form)
        self.label_38.setObjectName("label_38")
        self.formLayout_6.setWidget(8, QtGui.QFormLayout.LabelRole, self.label_38)
        self.saseenergy = QtGui.QLineEdit(Form)
        self.saseenergy.setStyleSheet("background-color: rgb(190, 190, 190);")
        self.saseenergy.setReadOnly(True)
        self.saseenergy.setObjectName("saseenergy")
        self.formLayout_6.setWidget(8, QtGui.QFormLayout.FieldRole, self.saseenergy)
        self.gridLayout.addLayout(self.formLayout_6, 1, 5, 6, 4)
        self.label_18 = QtGui.QLabel(Form)
        self.label_18.setObjectName("label_18")
        self.gridLayout.addWidget(self.label_18, 2, 2, 1, 2)
        self.label_8 = QtGui.QLabel(Form)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 3, 0, 1, 2)
        self.formLayout_4 = QtGui.QFormLayout()
        self.formLayout_4.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_4.setObjectName("formLayout_4")
        self.label_19 = QtGui.QLabel(Form)
        self.label_19.setObjectName("label_19")
        self.formLayout_4.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_19)
        self.rmssize = QtGui.QLineEdit(Form)
        self.rmssize.setStyleSheet("background-color: rgb(190, 190, 190);")
        self.rmssize.setReadOnly(True)
        self.rmssize.setObjectName("rmssize")
        self.formLayout_4.setWidget(0, QtGui.QFormLayout.FieldRole, self.rmssize)
        self.label_20 = QtGui.QLabel(Form)
        self.label_20.setObjectName("label_20")
        self.formLayout_4.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_20)
        self.uparam = QtGui.QLineEdit(Form)
        self.uparam.setStyleSheet("background-color: rgb(190, 190, 190);")
        self.uparam.setReadOnly(True)
        self.uparam.setObjectName("uparam")
        self.formLayout_4.setWidget(2, QtGui.QFormLayout.FieldRole, self.uparam)
        self.label_21 = QtGui.QLabel(Form)
        self.label_21.setObjectName("label_21")
        self.formLayout_4.setWidget(3, QtGui.QFormLayout.LabelRole, self.label_21)
        self.uwave = QtGui.QLineEdit(Form)
        self.uwave.setStyleSheet("background-color: rgb(190, 190, 190);")
        self.uwave.setReadOnly(True)
        self.uwave.setObjectName("uwave")
        self.formLayout_4.setWidget(3, QtGui.QFormLayout.FieldRole, self.uwave)
        self.label_9 = QtGui.QLabel(Form)
        self.label_9.setObjectName("label_9")
        self.formLayout_4.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_9)
        self.uperiod = QtGui.QLineEdit(Form)
        self.uperiod.setStyleSheet("background-color: rgb(190, 190, 190);")
        self.uperiod.setReadOnly(True)
        self.uperiod.setObjectName("uperiod")
        self.formLayout_4.setWidget(1, QtGui.QFormLayout.FieldRole, self.uperiod)
        self.gridLayout.addLayout(self.formLayout_4, 3, 2, 2, 2)
        self.formLayout_2 = QtGui.QFormLayout()
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_10 = QtGui.QLabel(Form)
        self.label_10.setObjectName("label_10")
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_10)
        self.ufield = QtGui.QLineEdit(Form)
        self.ufield.setObjectName("ufield")
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.FieldRole, self.ufield)
        self.label_11 = QtGui.QLabel(Form)
        self.label_11.setObjectName("label_11")
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_11)
        self.beta = QtGui.QLineEdit(Form)
        self.beta.setObjectName("beta")
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.FieldRole, self.beta)
        self.label_24 = QtGui.QLabel(Form)
        self.label_24.setObjectName("label_24")
        self.formLayout_2.setWidget(3, QtGui.QFormLayout.LabelRole, self.label_24)
        self.radiatedwavelength = QtGui.QLineEdit(Form)
        self.radiatedwavelength.setStyleSheet("")
        self.radiatedwavelength.setReadOnly(False)
        self.radiatedwavelength.setObjectName("radiatedwavelength")
        self.formLayout_2.setWidget(3, QtGui.QFormLayout.FieldRole, self.radiatedwavelength)
        self.gridLayout.addLayout(self.formLayout_2, 4, 0, 1, 1)
        self.label_39 = QtGui.QLabel(Form)
        self.label_39.setObjectName("label_39")
        self.gridLayout.addWidget(self.label_39, 5, 0, 1, 3)
        self.tableWidget = QtGui.QTableWidget(Form)
        self.tableWidget.setRowCount(6)
        self.tableWidget.setColumnCount(4)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(4)
        self.tableWidget.setRowCount(6)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(0, 0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(0, 1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(0, 2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(0, 3, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(1, 0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(1, 1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(1, 2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(1, 3, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(2, 0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(2, 1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(2, 2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(2, 3, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(3, 0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(3, 1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(3, 2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(3, 3, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(4, 0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(4, 1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(4, 2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(4, 3, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(5, 0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(5, 1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(5, 2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(5, 3, item)
        self.gridLayout.addWidget(self.tableWidget, 6, 0, 10, 4)
        self.label_43 = QtGui.QLabel(Form)
        self.label_43.setObjectName("label_43")
        self.gridLayout.addWidget(self.label_43, 6, 12, 2, 1)
        self.label_44 = QtGui.QLabel(Form)
        self.label_44.setObjectName("label_44")
        self.gridLayout.addWidget(self.label_44, 6, 13, 2, 1)
        self.label_22 = QtGui.QLabel(Form)
        self.label_22.setObjectName("label_22")
        self.gridLayout.addWidget(self.label_22, 7, 6, 2, 1)
        self.label_40 = QtGui.QLabel(Form)
        self.label_40.setObjectName("label_40")
        self.gridLayout.addWidget(self.label_40, 8, 10, 2, 1)
        self.x = QtGui.QComboBox(Form)
        self.x.setObjectName("x")
        self.gridLayout.addWidget(self.x, 8, 11, 2, 1)
        self.xmin = QtGui.QLineEdit(Form)
        self.xmin.setObjectName("xmin")
        self.gridLayout.addWidget(self.xmin, 8, 12, 2, 1)
        self.xmax = QtGui.QLineEdit(Form)
        self.xmax.setObjectName("xmax")
        self.gridLayout.addWidget(self.xmax, 8, 13, 2, 1)
        self.formLayout_5 = QtGui.QFormLayout()
        self.formLayout_5.setObjectName("formLayout_5")
        self.label_23 = QtGui.QLabel(Form)
        self.label_23.setObjectName("label_23")
        self.formLayout_5.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_23)
        self.averagepower = QtGui.QLineEdit(Form)
        self.averagepower.setStyleSheet("background-color: rgb(190, 190, 190);")
        self.averagepower.setReadOnly(True)
        self.averagepower.setObjectName("averagepower")
        self.formLayout_5.setWidget(0, QtGui.QFormLayout.FieldRole, self.averagepower)
        self.label_25 = QtGui.QLabel(Form)
        self.label_25.setObjectName("label_25")
        self.formLayout_5.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_25)
        self.saturation = QtGui.QLineEdit(Form)
        self.saturation.setStyleSheet("background-color: rgb(190, 190, 190);")
        self.saturation.setReadOnly(True)
        self.saturation.setObjectName("saturation")
        self.formLayout_5.setWidget(2, QtGui.QFormLayout.FieldRole, self.saturation)
        self.gridLayout.addLayout(self.formLayout_5, 9, 5, 3, 4)
        self.label_41 = QtGui.QLabel(Form)
        self.label_41.setObjectName("label_41")
        self.gridLayout.addWidget(self.label_41, 10, 10, 1, 1)
        self.y = QtGui.QComboBox(Form)
        self.y.setObjectName("y")
        self.gridLayout.addWidget(self.y, 10, 11, 1, 1)
        self.ymin = QtGui.QLineEdit(Form)
        self.ymin.setObjectName("ymin")
        self.gridLayout.addWidget(self.ymin, 10, 12, 1, 1)
        self.ymax = QtGui.QLineEdit(Form)
        self.ymax.setObjectName("ymax")
        self.gridLayout.addWidget(self.ymax, 10, 13, 1, 1)
        self.label_42 = QtGui.QLabel(Form)
        self.label_42.setObjectName("label_42")
        self.gridLayout.addWidget(self.label_42, 11, 10, 1, 1)
        self.z = QtGui.QComboBox(Form)
        self.z.setSizeAdjustPolicy(QtGui.QComboBox.AdjustToContentsOnFirstShow)
        self.z.setObjectName("z")
        self.gridLayout.addWidget(self.z, 11, 11, 1, 1)
        self.label_45 = QtGui.QLabel(Form)
        self.label_45.setObjectName("label_45")
        self.gridLayout.addWidget(self.label_45, 12, 6, 1, 2)
        self.label_46 = QtGui.QLabel(Form)
        self.label_46.setObjectName("label_46")
        self.gridLayout.addWidget(self.label_46, 13, 5, 1, 1)
        self.target = QtGui.QComboBox(Form)
        self.target.setObjectName("target")
        self.gridLayout.addWidget(self.target, 13, 6, 1, 2)
        self.label_47 = QtGui.QLabel(Form)
        self.label_47.setObjectName("label_47")
        self.gridLayout.addWidget(self.label_47, 13, 8, 1, 1)
        self.lineEdit = QtGui.QLineEdit(Form)
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout.addWidget(self.lineEdit, 13, 9, 1, 1)
        self.pushButton = QtGui.QPushButton(Form)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout.addWidget(self.pushButton, 13, 11, 3, 3)
        self.label_48 = QtGui.QLabel(Form)
        self.label_48.setObjectName("label_48")
        self.gridLayout.addWidget(self.label_48, 14, 5, 1, 1)
        self.vary = QtGui.QComboBox(Form)
        self.vary.setObjectName("vary")
        self.gridLayout.addWidget(self.vary, 14, 6, 1, 2)
        self.solve = QtGui.QPushButton(Form)
        self.solve.setObjectName("solve")
        self.gridLayout.addWidget(self.solve, 15, 6, 1, 1)
        self.lineEdit_4 = QtGui.QLineEdit(Form)
        self.lineEdit_4.setStyleSheet("background-color: rgb(186, 186, 186);")
        self.lineEdit_4.setText("")
        self.lineEdit_4.setReadOnly(True)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.gridLayout.addWidget(self.lineEdit_4, 15, 7, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(QtGui.QApplication.translate("Form", "Form", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("Form", "E-Beam Inputs", None, QtGui.QApplication.UnicodeUTF8))
        self.label_12.setText(QtGui.QApplication.translate("Form", "E-Beam Parameters", None, QtGui.QApplication.UnicodeUTF8))
        self.label_26.setText(QtGui.QApplication.translate("Form", "FEL Performance", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("Form", "Charge:", None, QtGui.QApplication.UnicodeUTF8))
        self.charge.setToolTip(QtGui.QApplication.translate("Form", "pC", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("Form", "Normalized slice emittance:", None, QtGui.QApplication.UnicodeUTF8))
        self.slicemit.setToolTip(QtGui.QApplication.translate("Form", "mm-mrad", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("Form", "E-beam energy:", None, QtGui.QApplication.UnicodeUTF8))
        self.ebeamenergy.setToolTip(QtGui.QApplication.translate("Form", "MeV", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("Form", "Sliced energy spread:", None, QtGui.QApplication.UnicodeUTF8))
        self.energyspread.setToolTip(QtGui.QApplication.translate("Form", "%", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("Form", "Repetition rate:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_17.setText(QtGui.QApplication.translate("Form", "Peak current:", None, QtGui.QApplication.UnicodeUTF8))
        self.peakamp.setToolTip(QtGui.QApplication.translate("Form", "A", None, QtGui.QApplication.UnicodeUTF8))
        self.label_13.setText(QtGui.QApplication.translate("Form", "Bunch length(distance):", None, QtGui.QApplication.UnicodeUTF8))
        self.bunlen.setToolTip(QtGui.QApplication.translate("Form", "FWHM", None, QtGui.QApplication.UnicodeUTF8))
        self.label_14.setText(QtGui.QApplication.translate("Form", "Gamma:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_15.setText(QtGui.QApplication.translate("Form", "Peak electron density:", None, QtGui.QApplication.UnicodeUTF8))
        self.edensity.setToolTip(QtGui.QApplication.translate("Form", "1/m^3", None, QtGui.QApplication.UnicodeUTF8))
        self.label_16.setText(QtGui.QApplication.translate("Form", "Geometric emittance:", None, QtGui.QApplication.UnicodeUTF8))
        self.geoemit.setToolTip(QtGui.QApplication.translate("Form", "nm", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("Form", "Bunch length(time):", None, QtGui.QApplication.UnicodeUTF8))
        self.bunchlen.setToolTip(QtGui.QApplication.translate("Form", "FWHM", None, QtGui.QApplication.UnicodeUTF8))
        self.label_27.setText(QtGui.QApplication.translate("Form", "Rayleigh range:", None, QtGui.QApplication.UnicodeUTF8))
        self.raleigh.setToolTip(QtGui.QApplication.translate("Form", "cm", None, QtGui.QApplication.UnicodeUTF8))
        self.label_28.setText(QtGui.QApplication.translate("Form", "Photon emittance:", None, QtGui.QApplication.UnicodeUTF8))
        self.photonemit.setToolTip(QtGui.QApplication.translate("Form", "nm", None, QtGui.QApplication.UnicodeUTF8))
        self.label_29.setText(QtGui.QApplication.translate("Form", "1D FEL parameter:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_30.setText(QtGui.QApplication.translate("Form", "1D gain length:", None, QtGui.QApplication.UnicodeUTF8))
        self.gain_1d.setToolTip(QtGui.QApplication.translate("Form", "cm", None, QtGui.QApplication.UnicodeUTF8))
        self.label_31.setText(QtGui.QApplication.translate("Form", "Diffraction factor:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_32.setText(QtGui.QApplication.translate("Form", "Emittance factor:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_33.setText(QtGui.QApplication.translate("Form", "Energy spread factor:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_34.setText(QtGui.QApplication.translate("Form", "3D FEL parameter:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_35.setText(QtGui.QApplication.translate("Form", "3D gain length:", None, QtGui.QApplication.UnicodeUTF8))
        self.gain_3d.setToolTip(QtGui.QApplication.translate("Form", "cm", None, QtGui.QApplication.UnicodeUTF8))
        self.label_36.setText(QtGui.QApplication.translate("Form", "3D effect total:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_37.setText(QtGui.QApplication.translate("Form", "SASE saturation power:", None, QtGui.QApplication.UnicodeUTF8))
        self.sasepower.setToolTip(QtGui.QApplication.translate("Form", "GW", None, QtGui.QApplication.UnicodeUTF8))
        self.label_38.setText(QtGui.QApplication.translate("Form", "SASE pulsed energy:", None, QtGui.QApplication.UnicodeUTF8))
        self.saseenergy.setToolTip(QtGui.QApplication.translate("Form", "mJ", None, QtGui.QApplication.UnicodeUTF8))
        self.label_18.setText(QtGui.QApplication.translate("Form", "Undulator and Focusing Parameters", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("Form", "Undulator and Focusing Inputs", None, QtGui.QApplication.UnicodeUTF8))
        self.label_19.setText(QtGui.QApplication.translate("Form", "RMS beam size(average):", None, QtGui.QApplication.UnicodeUTF8))
        self.rmssize.setToolTip(QtGui.QApplication.translate("Form", "um", None, QtGui.QApplication.UnicodeUTF8))
        self.label_20.setText(QtGui.QApplication.translate("Form", "Undulator parameter:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_21.setText(QtGui.QApplication.translate("Form", "Undulator wavenumber:", None, QtGui.QApplication.UnicodeUTF8))
        self.uwave.setToolTip(QtGui.QApplication.translate("Form", "1/m", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("Form", "Undulator period:", None, QtGui.QApplication.UnicodeUTF8))
        self.uperiod.setToolTip(QtGui.QApplication.translate("Form", "mm", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("Form", "Undulator field:", None, QtGui.QApplication.UnicodeUTF8))
        self.ufield.setToolTip(QtGui.QApplication.translate("Form", "T", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("Form", "Average beta function:", None, QtGui.QApplication.UnicodeUTF8))
        self.beta.setToolTip(QtGui.QApplication.translate("Form", "m", None, QtGui.QApplication.UnicodeUTF8))
        self.label_24.setText(QtGui.QApplication.translate("Form", "Radiated wavelength:", None, QtGui.QApplication.UnicodeUTF8))
        self.radiatedwavelength.setToolTip(QtGui.QApplication.translate("Form", "nm", None, QtGui.QApplication.UnicodeUTF8))
        #self.label_39.setText(QtGui.QApplication.translate("Form",
        # "Ming Xie Matrix", None, QtGui.QApplication.UnicodeUTF8))
        __sortingEnabled = self.tableWidget.isSortingEnabled()
        self.tableWidget.setSortingEnabled(False)
        self.tableWidget.setVisible(False)
        self.tableWidget.item(0, 0).setText(QtGui.QApplication.translate("Form", "0.55", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget.item(0, 1).setText(QtGui.QApplication.translate("Form", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget.item(0, 2).setText(QtGui.QApplication.translate("Form", "1.6", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget.item(0, 3).setText(QtGui.QApplication.translate("Form", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget.item(1, 0).setText(QtGui.QApplication.translate("Form", "3.0", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget.item(1, 1).setText(QtGui.QApplication.translate("Form", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget.item(1, 2).setText(QtGui.QApplication.translate("Form", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget.item(1, 3).setText(QtGui.QApplication.translate("Form", "2.0", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget.item(2, 0).setText(QtGui.QApplication.translate("Form", "0.35", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget.item(2, 1).setText(QtGui.QApplication.translate("Form", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget.item(2, 2).setText(QtGui.QApplication.translate("Form", "2.9", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget.item(2, 3).setText(QtGui.QApplication.translate("Form", "2.4", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget.item(3, 0).setText(QtGui.QApplication.translate("Form", "51", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget.item(3, 1).setText(QtGui.QApplication.translate("Form", "0.95", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget.item(3, 2).setText(QtGui.QApplication.translate("Form", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget.item(3, 3).setText(QtGui.QApplication.translate("Form", "3.0", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget.item(4, 0).setText(QtGui.QApplication.translate("Form", "5.4", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget.item(4, 1).setText(QtGui.QApplication.translate("Form", "0.7", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget.item(4, 2).setText(QtGui.QApplication.translate("Form", "1.9", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget.item(4, 3).setText(QtGui.QApplication.translate("Form", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget.item(5, 0).setText(QtGui.QApplication.translate("Form", "1140", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget.item(5, 1).setText(QtGui.QApplication.translate("Form", "2.2", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget.item(5, 2).setText(QtGui.QApplication.translate("Form", "2.9", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget.item(5, 3).setText(QtGui.QApplication.translate("Form", "3.2", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget.setSortingEnabled(__sortingEnabled)
        self.label_43.setText(QtGui.QApplication.translate("Form", "min", None, QtGui.QApplication.UnicodeUTF8))
        self.label_44.setText(QtGui.QApplication.translate("Form", "max", None, QtGui.QApplication.UnicodeUTF8))
        self.label_22.setText(QtGui.QApplication.translate("Form", "FEL Output", None, QtGui.QApplication.UnicodeUTF8))
        self.label_40.setText(QtGui.QApplication.translate("Form", "x:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_23.setText(QtGui.QApplication.translate("Form", "Average power:", None, QtGui.QApplication.UnicodeUTF8))
        self.averagepower.setToolTip(QtGui.QApplication.translate("Form", "W", None, QtGui.QApplication.UnicodeUTF8))
        self.label_25.setText(QtGui.QApplication.translate("Form", "Saturation length:", None, QtGui.QApplication.UnicodeUTF8))
        self.saturation.setToolTip(QtGui.QApplication.translate("Form", "m", None, QtGui.QApplication.UnicodeUTF8))
        self.label_41.setText(QtGui.QApplication.translate("Form", "y:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_42.setText(QtGui.QApplication.translate("Form", "z:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_45.setText(QtGui.QApplication.translate("Form", "FEL Solver", None, QtGui.QApplication.UnicodeUTF8))
        self.label_46.setText(QtGui.QApplication.translate("Form", "Target", None, QtGui.QApplication.UnicodeUTF8))
        self.label_47.setText(QtGui.QApplication.translate("Form", "to", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton.setText(QtGui.QApplication.translate("Form", "Plot", None, QtGui.QApplication.UnicodeUTF8))
        self.label_48.setText(QtGui.QApplication.translate("Form", "Varying", None, QtGui.QApplication.UnicodeUTF8))
        self.solve.setText(QtGui.QApplication.translate("Form", "Solve", None, QtGui.QApplication.UnicodeUTF8))

from RadTrack.gui.matplotlibwidget import matplotlibWidget
